kind: Build
apiVersion: garden.io/v2
name: bolabaden-nextjs
description: Bolabaden NextJS main website build
type: container
source:
  path: ${var.src-path || "./src"}/website/bolabaden-site

---
kind: Deploy
apiVersion: garden.io/v2
name: bolabaden-nextjs
description: Bolabaden NextJS main website container
type: container
dependencies:
  - build.bolabaden-nextjs

spec:
  image: ${actions.build.bolabaden-nextjs.outputs.deploymentImageId}
  env:
    TZ: ${var.tz}
    PUID: ${var.PUID || "1001"}
    PGID: ${var.PGID || "999"}
    UMASK: ${var.UMASK || "002"}
    NODE_ENV: production
    PORT: 3000
    HOSTNAME: 0.0.0.0
    ALLOW_ORIGIN: "*"
  ports:
    - name: http
      containerPort: 3000
  ingresses:
    - path: /
      port: http
      hostname: ${var.domain}
    - path: /api/error
      port: http
      hostname: ${var.domain}
  healthCheck:
    httpGet:
      path: /
      port: http
  restartPolicy: always
