kind: Build
apiVersion: garden.io/v0
name: bolabaden-nextjs
description: Bolabaden NextJS main website build
type: container
source:
  path: ${var.src-path || "./src"}/website/bolabaden-site

---
kind: Deploy
apiVersion: garden.io/v0
name: bolabaden-nextjs
description: Bolabaden NextJS main website container
type: container
dependencies:
  - build.bolabaden-nextjs

spec:
  replicas: 3
  image: docker.io/bolabaden/bolabaden-nextjs
  hostname: bolabaden-nextjs
  env:
    TZ: ${var.tz}
    PUID: ${var.PUID || "1001"}
    PGID: ${var.PGID || "999"}
    UMASK: ${var.UMASK || "002"}
    NODE_ENV: production
    PORT: 3000
    HOSTNAME: 0.0.0.0
    ALLOW_ORIGIN: "*"
  ports:
    - name: http
      containerPort: 3000
  ingresses:
    - path: /
      port: http
      hostname: ${var.domain}
    - path: /
      port: http
      hostname: ${var.ts-hostname}.${var.domain}
  annotations:
    traefik.enable: "true"
    traefik.http.middlewares.bolabaden-error-pages.errors.status: "400-599"
    traefik.http.middlewares.bolabaden-error-pages.errors.service: bolabaden-nextjs@docker
    traefik.http.middlewares.bolabaden-error-pages.errors.query: /api/error/{status}
    traefik.http.routers.bolabaden-nextjs.rule: Host(`${var.domain}`) || Host(`${var.ts-hostname}.${var.domain}`)
    traefik.http.services.bolabaden-nextjs.loadbalancer.server.port: "3000"
    kuma.bolabaden-nextjs.http.name: ${var.ts-hostname}.${var.domain}
    kuma.bolabaden-nextjs.http.url: https://${var.domain}
    kuma.bolabaden-nextjs.http.interval: "30"
  healthCheck:
    exec:
      command:
      - sh
      - -c
      - 'wget -qO- http://127.0.0.1:${var.PORT || "3000"} > /dev/null 2>&1 || exit 1'
    initialDelaySeconds: 30
    timeoutSeconds: 10
  restartPolicy: always
