kind: Build
apiVersion: garden.io/v2
name: bolabaden-nextjs
description: Bolabaden NextJS main website build
type: container
source:
  path: ${var.src-path || "./src"}/website/bolabaden-site

---
kind: Deploy
apiVersion: garden.io/v2
name: bolabaden-nextjs
description: Bolabaden NextJS main website container
type: container
dependencies:
  - build.bolabaden-nextjs

spec:
  image: ${actions.build.bolabaden-nextjs.outputs.deploymentImageId}
  env:
    TZ: ${var.tz}
    PUID: ${var.PUID || "1001"}
    PGID: ${var.PGID || "999"}
    UMASK: ${var.UMASK || "002"}
    NODE_ENV: production
    PORT: 3000
    HOSTNAME: 0.0.0.0
    ALLOW_ORIGIN: "*"
  ports:
    - name: http
      containerPort: 3000
  ingresses:
    - path: /
      port: http
      hostname: ${var.domain}
    - path: /
      port: http
      hostname: ${var.ts-hostname}.${var.domain}
  healthCheck:
    exec:
      command:
      - sh
      - -c
      - 'wget -qO- http://127.0.0.1:${var.PORT || "3000"} > /dev/null 2>&1 || exit 1'
    initialDelaySeconds: 30
    timeoutSeconds: 10
  restartPolicy: always
