kind: Deploy
apiVersion: garden.io/v0
name: redis
description: Redis cache and message broker
type: container

spec:
  replicas: 3
  image: docker.io/redis:alpine
  hostname: redis
  privileged: true
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    REDIS_HOST: ${var.REDIS_HOSTNAME || "redis"}
    REDIS_PORT: ${var.REDIS_PORT || "6379"}
    REDIS_DATABASE: ${var.REDIS_DATABASE || "0"}
    REDIS_USERNAME: ${var.REDIS_USERNAME || "default"}
    REDIS_PASSWORD: ${var.REDIS_PASSWORD || "redis"}
  ports:
    - name: redis
      containerPort: ${var.REDIS_PORT || "6379"}
      hostPort: ${var.REDIS_PORT || "6379"}
  volumes:
    - name: data
      containerPath: /data
      sourcePath: ${var.config-path}/redis
  command:
    - sh
    - -c
    - |
      sysctl vm.overcommit_memory=1 &> /dev/null &&
      redis-server
      --appendonly yes
      --save 60 1
      --bind 0.0.0.0
      --port $${REDIS_PORT:-6379}
      --requirepass $${REDIS_PASSWORD:?}
  resources:
    limits:
      cpu: 500m
      memory: 4Gi
    requests:
      memory: 200Mi
  ingresses:
    - path: /
      port: redis
      hostname: redis.${var.domain}
      protocol: TCP
    - path: /
      port: redis
      hostname: redis.${var.ts-hostname}.${var.domain}
      protocol: TCP
  annotations:
    traefik.enable: true
    traefik.tcp.routers.redis.rule: HostSNI(`redis.${var.domain}`) || HostSNI(`redis.${var.ts-hostname}.${var.domain}`)
    traefik.tcp.routers.redis.service: redis@docker
    traefik.tcp.routers.redis.tls.domains[0].main: ${var.domain}
    traefik.tcp.routers.redis.tls.domains[0].sans: *.${var.domain},${var.ts-hostname}.${var.domain}
    traefik.tcp.routers.redis.tls.passthrough: true
    traefik.tcp.services.redis.loadbalancer.server.port: $${REDIS_PORT:-6379}
    traefik.tcp.services.redis.loadbalancer.server.tls: true
  healthCheck:
    exec:
      command: [sh, -c, "redis-cli ping > /dev/null 2>&1 || exit 1"]
    initialDelaySeconds: 0
    periodSeconds: 10
    timeoutSeconds: 5
  restartPolicy: always
