kind: Deploy
apiVersion: garden.io/v2
name: searxng
description: SearxNG privacy-focused metasearch engine
type: container

spec:
  image: docker.io/searxng/searxng
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    SEARXNG_BASE_URL: ${var.SEARXNG_INTERNAL_URL || "http://searxng:8080"}
    SEARXNG_SECRET: ${var.SEARXNG_SECRET}
  ports:
    - name: http
      containerPort: ${var.SEARXNG_PORT || "8080"}
  volumes:
    - name: config
      containerPath: /etc/searxng
      sourcePath: ${var.config-path}/searxng/config
    - name: data
      containerPath: /var/cache/searxng
      sourcePath: ${var.config-path}/searxng/data
  ingresses:
    - path: /
      port: http
      hostname: searxng.${var.domain}
  healthCheck:
    exec:
      command:
      - sh
      - -c
      - 'wget --no-verbose --tries=1 --spider http://127.0.0.1:${var.SEARXNG_PORT || "8080"}/ || exit 1'
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  restartPolicy: always
