kind: Deploy
apiVersion: garden.io/v0
name: gptr
description: AI Research Wizard full-stack application
type: container

spec:
  replicas: 3
  image: docker.io/bolabaden/ai-researchwizard-aio-fullstack:master
  hostname: gptr
  extraHosts:
    - host.docker.internal:host-gateway
  stdinOpen: true
  env:
    ANTHROPIC_API_KEY_FILE: /run/secrets/anthropic-api-key
    BRAVE_API_KEY_FILE: /run/secrets/brave-api-key
    DEEPSEEK_API_KEY_FILE: /run/secrets/deepseek-api-key
    EXA_API_KEY_FILE: /run/secrets/exa-api-key
    FIRECRAWL_API_KEY_FILE: /run/secrets/firecrawl-api-key
    FIRE_CRAWL_API_KEY_FILE: /run/secrets/firecrawl-api-key
    GEMINI_API_KEY_FILE: /run/secrets/gemini-api-key
    GLAMA_API_KEY_FILE: /run/secrets/glama-api-key
    GROQ_API_KEY_FILE: /run/secrets/groq-api-key
    HF_TOKEN_FILE: /run/secrets/hf-token
    HUGGINGFACE_ACCESS_TOKEN_FILE: /run/secrets/hf-token
    HUGGINGFACE_API_TOKEN_FILE: /run/secrets/hf-token
    LANGCHAIN_API_KEY_FILE: /run/secrets/langchain-api-key
    MISTRAL_API_KEY_FILE: /run/secrets/mistral-api-key
    MISTRALAI_API_KEY_FILE: /run/secrets/mistral-api-key
    OPENAI_API_KEY_FILE: /run/secrets/openai-api-key
    OPENROUTER_API_KEY_FILE: /run/secrets/openrouter-api-key
    PERPLEXITY_API_KEY_FILE: /run/secrets/perplexity-api-key
    PERPLEXITYAI_API_KEY_FILE: /run/secrets/perplexity-api-key
    REPLICATE_API_KEY_FILE: /run/secrets/replicate-api-key
    REVID_API_KEY_FILE: /run/secrets/revid-api-key
    SAMBANOVA_API_KEY_FILE: /run/secrets/sambanova-api-key
    SEARCH1API_KEY_FILE: /run/secrets/search1api-key
    SERPAPI_API_KEY_FILE: /run/secrets/serpapi-api-key
    TAVILY_API_KEY_FILE: /run/secrets/tavily-api-key
    TOGETHERAI_API_KEY_FILE: /run/secrets/togetherai-api-key
    UPSTAGE_API_KEY_FILE: /run/secrets/upstage-api-key
    UPSTAGEAI_API_KEY_FILE: /run/secrets/upstage-api-key
    LANGSMITH_API_KEY_FILE: /run/secrets/langchain-api-key
    CHOKIDAR_USEPOLLING: ${var.CHOKIDAR_USEPOLLING || "true"}
    LOGGING_LEVEL: ${var.GPTR_LOGGING_LEVEL || "DEBUG"}
    NEXT_PUBLIC_GA_MEASUREMENT_ID: ${var.NEXT_PUBLIC_GA_MEASUREMENT_ID}
    NEXT_PUBLIC_GPTR_API_URL: https://gptr.${var.domain}
    LANGSMITH_TRACING: ${var.LANGSMITH_TRACING || "true"}
    LANGSMITH_ENDPOINT: ${var.LANGSMITH_ENDPOINT || "https://api.smith.langchain.com"}
  ports:
    - name: nginx
      containerPort: 3000
    - name: nextjs
      containerPort: 3001
    - name: static
      containerPort: 8000
    - name: mcp
      containerPort: 8080
  volumes:
    - name: logs
      containerPath: /usr/src/app/logs
      hostPath: ${var.config-path}/gptr/logs
    - name: outputs
      containerPath: /usr/src/app/outputs
      hostPath: ${var.config-path}/gptr/outputs
    - name: reports
      containerPath: /usr/src/app/reports
      hostPath: ${var.config-path}/gptr/reports
    - name: anthropic-api-key
      containerPath: /run/secrets/anthropic-api-key
      hostPath: ${var.config-path}/secrets/anthropic-api-key.txt
      readOnly: true
    - name: brave-api-key
      containerPath: /run/secrets/brave-api-key
      hostPath: ${var.config-path}/secrets/brave-api-key.txt
      readOnly: true
    - name: deepseek-api-key
      containerPath: /run/secrets/deepseek-api-key
      hostPath: ${var.config-path}/secrets/deepseek-api-key.txt
      readOnly: true
    - name: exa-api-key
      containerPath: /run/secrets/exa-api-key
      hostPath: ${var.config-path}/secrets/exa-api-key.txt
      readOnly: true
    - name: firecrawl-api-key
      containerPath: /run/secrets/firecrawl-api-key
      hostPath: ${var.config-path}/secrets/firecrawl-api-key.txt
      readOnly: true
    - name: gemini-api-key
      containerPath: /run/secrets/gemini-api-key
      hostPath: ${var.config-path}/secrets/gemini-api-key.txt
      readOnly: true
    - name: glama-api-key
      containerPath: /run/secrets/glama-api-key
      hostPath: ${var.config-path}/secrets/glama-api-key.txt
      readOnly: true
    - name: groq-api-key
      containerPath: /run/secrets/groq-api-key
      hostPath: ${var.config-path}/secrets/groq-api-key.txt
      readOnly: true
    - name: hf-token
      containerPath: /run/secrets/hf-token
      hostPath: ${var.config-path}/secrets/hf-token.txt
      readOnly: true
    - name: langchain-api-key
      containerPath: /run/secrets/langchain-api-key
      hostPath: ${var.config-path}/secrets/langchain-api-key.txt
      readOnly: true
    - name: mistral-api-key
      containerPath: /run/secrets/mistral-api-key
      hostPath: ${var.config-path}/secrets/mistral-api-key.txt
      readOnly: true
    - name: openai-api-key
      containerPath: /run/secrets/openai-api-key
      hostPath: ${var.config-path}/secrets/openai-api-key.txt
      readOnly: true
    - name: openrouter-api-key
      containerPath: /run/secrets/openrouter-api-key
      hostPath: ${var.config-path}/secrets/openrouter-api-key.txt
      readOnly: true
    - name: perplexity-api-key
      containerPath: /run/secrets/perplexity-api-key
      hostPath: ${var.config-path}/secrets/perplexity-api-key.txt
      readOnly: true
    - name: replicate-api-key
      containerPath: /run/secrets/replicate-api-key
      hostPath: ${var.config-path}/secrets/replicate-api-key.txt
      readOnly: true
    - name: revid-api-key
      containerPath: /run/secrets/revid-api-key
      hostPath: ${var.config-path}/secrets/revid-api-key.txt
      readOnly: true
    - name: sambanova-api-key
      containerPath: /run/secrets/sambanova-api-key
      hostPath: ${var.config-path}/secrets/sambanova-api-key.txt
      readOnly: true
    - name: search1api-key
      containerPath: /run/secrets/search1api-key
      hostPath: ${var.config-path}/secrets/search1api-key.txt
      readOnly: true
    - name: serpapi-api-key
      containerPath: /run/secrets/serpapi-api-key
      hostPath: ${var.config-path}/secrets/serpapi-api-key.txt
      readOnly: true
    - name: tavily-api-key
      containerPath: /run/secrets/tavily-api-key
      hostPath: ${var.config-path}/secrets/tavily-api-key.txt
      readOnly: true
    - name: togetherai-api-key
      containerPath: /run/secrets/togetherai-api-key
      hostPath: ${var.config-path}/secrets/togetherai-api-key.txt
      readOnly: true
    - name: upstage-api-key
      containerPath: /run/secrets/upstage-api-key
      hostPath: ${var.config-path}/secrets/upstage-api-key.txt
      readOnly: true
  ingresses:
    - path: /
      port: nginx
      hostname: gptr-nextjs.${var.domain}
    - path: /
      port: nginx
      hostname: gptr-nextjs.${var.ts-hostname}.${var.domain}
    - path: /
      port: static
      hostname: gptr.${var.domain}
    - path: /
      port: static
      hostname: gptr.${var.ts-hostname}.${var.domain}
    - path: /
      port: mcp
      hostname: gptr-mcp.${var.domain}
    - path: /
      port: mcp
      hostname: gptr-mcp.${var.ts-hostname}.${var.domain}
  annotations:
    traefik.enable: "true"
    traefik.http.routers.gptr-nextjs.service: gptr-nextjs@docker
    traefik.http.routers.gptr-nextjs.rule: Host(`gptr-nextjs.${var.domain}`) || Host(`gptr-nextjs.${var.ts-hostname}.${var.domain}`)
    traefik.http.services.gptr-nextjs.loadbalancer.server.port: "3000"
    traefik.http.routers.gptr-legacy.service: gptr-legacy@docker
    traefik.http.routers.gptr-legacy.rule: Host(`gptr.${var.domain}`) || Host(`gptr.${var.ts-hostname}.${var.domain}`)
    traefik.http.services.gptr-legacy.loadbalancer.server.port: "8000"
    traefik.http.routers.gptr-mcp.service: gptr-mcp@docker
    traefik.http.routers.gptr-mcp.rule: Host(`gptr-mcp.${var.domain}`) || Host(`gptr-mcp.${var.ts-hostname}.${var.domain}`)
    traefik.http.services.gptr-mcp.loadbalancer.server.port: "8080"
    homepage.group: AI
    homepage.name: AI Research Wizard
    homepage.description: Full-stack AI research and scraping toolkit with Next.js UI is a web scraper and researcher that uses AI to help you find information quickly.
    homepage.icon: gptr.png
    homepage.href: https://gptr.${var.domain}/
    kuma.gptr.http.name: gptr.${var.ts-hostname}.${var.domain}
    kuma.gptr.http.url: https://gptr.${var.domain}
    kuma.gptr.http.interval: "30"
  healthCheck:
    exec:
      command: [sh, -c, "(wget -qO- http://127.0.0.1:3000 > /dev/null 2>&1 && wget -qO- http://127.0.0.1:8000 > /dev/null 2>&1) || exit 1"]
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
    startPeriodSeconds: 120
  restartPolicy: always
