kind: Deploy
apiVersion: garden.io/v2
name: litellm
description: LiteLLM gateway for multiple LLM providers
type: container
dependencies:
  - deploy.litellm-postgres
  - deploy.redis

spec:
  image: ghcr.io/berriai/litellm-database:main-stable
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    LITELLM_LOG: ${var.LITELLM_LOG || "INFO"}
    LITELLM_MASTER_KEY_FILE: /run/secrets/litellm-master-key
    LITELLM_MODE: ${var.LITELLM_MODE || "PRODUCTION"}
    UI_USERNAME: ${var.LITELLM_UI_USERNAME || "admin"}
    UI_PASSWORD_FILE: /run/secrets/litellm-master-key
    DATABASE_URL: postgresql://${var.LITELLM_POSTGRES_USER || "litellm"}:${var.LITELLM_POSTGRES_PASSWORD || "litellm"}@${var.LITELLM_POSTGRES_HOSTNAME || "litellm-postgres"}:5432/${var.LITELLM_POSTGRES_DB || "litellm"}
    REDIS_HOST: ${var.REDIS_HOSTNAME || "redis"}
    REDIS_PORT: ${var.REDIS_PORT || "6379"}
    POSTGRES_USER: ${var.LITELLM_POSTGRES_USER || "litellm"}
    POSTGRES_PASSWORD: ${var.LITELLM_POSTGRES_PASSWORD || "litellm"}
    POSTGRES_DB: ${var.LITELLM_POSTGRES_DB || "litellm"}
    ANTHROPIC_API_KEY_FILE: /run/secrets/anthropic-api-key
    OPENAI_API_KEY_FILE: /run/secrets/openai-api-key
    OPENROUTER_API_KEY_FILE: /run/secrets/openrouter-api-key
    GROQ_API_KEY_FILE: /run/secrets/groq-api-key
    DEEPSEEK_API_KEY_FILE: /run/secrets/deepseek-api-key
    GEMINI_API_KEY_FILE: /run/secrets/gemini-api-key
    MISTRAL_API_KEY_FILE: /run/secrets/mistral-api-key
    PERPLEXITY_API_KEY_FILE: /run/secrets/perplexity-api-key
    REPLICATE_API_KEY_FILE: /run/secrets/replicate-api-key
    SAMBANOVA_API_KEY_FILE: /run/secrets/sambanova-api-key
    TOGETHERAI_API_KEY_FILE: /run/secrets/togetherai-api-key
    HF_TOKEN_FILE: /run/secrets/hf-token
    LANGCHAIN_API_KEY_FILE: /run/secrets/langchain-api-key
    SERPAPI_API_KEY_FILE: /run/secrets/serpapi-api-key
    SEARCH1API_KEY_FILE: /run/secrets/search1api-key
    UPSTAGE_API_KEY_FILE: /run/secrets/upstage-api-key
    JINA_API_KEY_FILE: /run/secrets/jina-api-key
    KAGI_API_KEY_FILE: /run/secrets/kagi-api-key
    GLAMA_API_KEY_FILE: /run/secrets/glama-api-key
  ports:
    - name: http
      containerPort: ${var.LITELLM_PORT || "4000"}
  volumes:
    - name: config
      containerPath: /app/config
      sourcePath: ${var.config-path}/litellm
      readOnly: true
    - name: litellm-config-yaml
      containerPath: /app/config/litellm_config.yaml
      sourcePath: ${var.config-path}/litellm/litellm_config.yaml
      readOnly: true
    - name: litellm-master-key
      containerPath: /run/secrets/litellm-master-key
      sourcePath: ${var.config-path}/secrets/litellm-master-key.txt
      readOnly: true
    - name: anthropic-api-key
      containerPath: /run/secrets/anthropic-api-key
      sourcePath: ${var.config-path}/secrets/anthropic-api-key.txt
      readOnly: true
    - name: openai-api-key
      containerPath: /run/secrets/openai-api-key
      sourcePath: ${var.config-path}/secrets/openai-api-key.txt
      readOnly: true
    - name: openrouter-api-key
      containerPath: /run/secrets/openrouter-api-key
      sourcePath: ${var.config-path}/secrets/openrouter-api-key.txt
      readOnly: true
    - name: groq-api-key
      containerPath: /run/secrets/groq-api-key
      sourcePath: ${var.config-path}/secrets/groq-api-key.txt
      readOnly: true
    - name: deepseek-api-key
      containerPath: /run/secrets/deepseek-api-key
      sourcePath: ${var.config-path}/secrets/deepseek-api-key.txt
      readOnly: true
    - name: gemini-api-key
      containerPath: /run/secrets/gemini-api-key
      sourcePath: ${var.config-path}/secrets/gemini-api-key.txt
      readOnly: true
    - name: mistral-api-key
      containerPath: /run/secrets/mistral-api-key
      sourcePath: ${var.config-path}/secrets/mistral-api-key.txt
      readOnly: true
    - name: perplexity-api-key
      containerPath: /run/secrets/perplexity-api-key
      sourcePath: ${var.config-path}/secrets/perplexity-api-key.txt
      readOnly: true
    - name: replicate-api-key
      containerPath: /run/secrets/replicate-api-key
      sourcePath: ${var.config-path}/secrets/replicate-api-key.txt
      readOnly: true
    - name: sambanova-api-key
      containerPath: /run/secrets/sambanova-api-key
      sourcePath: ${var.config-path}/secrets/sambanova-api-key.txt
      readOnly: true
    - name: togetherai-api-key
      containerPath: /run/secrets/togetherai-api-key
      sourcePath: ${var.config-path}/secrets/togetherai-api-key.txt
      readOnly: true
    - name: hf-token
      containerPath: /run/secrets/hf-token
      sourcePath: ${var.config-path}/secrets/hf-token.txt
      readOnly: true
    - name: langchain-api-key
      containerPath: /run/secrets/langchain-api-key
      sourcePath: ${var.config-path}/secrets/langchain-api-key.txt
      readOnly: true
    - name: serpapi-api-key
      containerPath: /run/secrets/serpapi-api-key
      sourcePath: ${var.config-path}/secrets/serpapi-api-key.txt
      readOnly: true
    - name: search1api-key
      containerPath: /run/secrets/search1api-key
      sourcePath: ${var.config-path}/secrets/search1api-key.txt
      readOnly: true
    - name: upstage-api-key
      containerPath: /run/secrets/upstage-api-key
      sourcePath: ${var.config-path}/secrets/upstage-api-key.txt
      readOnly: true
    - name: jina-api-key
      containerPath: /run/secrets/jina-api-key
      sourcePath: ${var.config-path}/secrets/jina-api-key.txt
      readOnly: true
    - name: kagi-api-key
      containerPath: /run/secrets/kagi-api-key
      sourcePath: ${var.config-path}/secrets/kagi-api-key.txt
      readOnly: true
    - name: glama-api-key
      containerPath: /run/secrets/glama-api-key
      sourcePath: ${var.config-path}/secrets/glama-api-key.txt
      readOnly: true
  command: [--config, /app/config/litellm_config.yaml, --port, ${var.LITELLM_PORT || "4000"}, --host, 0.0.0.0]
  ingresses:
    - path: /
      port: http
      hostname: litellm.${var.domain}
  healthCheck:
    exec:
      command: [sh, -c, "wget -qO- http://127.0.0.1:${var.LITELLM_PORT || "4000"}/health/liveliness"]
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 15
    failureThreshold: 5
  restartPolicy: always
