kind: Deploy
apiVersion: garden.io/v0
name: mcp-proxy
description: MCP Proxy for proxying MCP servers
type: container

spec:
  image: ghcr.io/tbxark/mcp-proxy
  extraHosts:
    - host.docker.internal:host-gateway
  ports:
    - name: http
      containerPort: ${var.MCP_PROXY_PORT || "9090"}
  volumes:
    - name: config
      containerPath: /config.json
      sourcePath: ${var.config-path}/mcp-proxy/config.json
      readOnly: true
  command:
    - --config
    - config.json
    - -expand-env
  ingresses:
    - path: /
      port: http
      hostname: mcp.${var.domain}
    - path: /
      port: http
      hostname: mcp.${var.ts-hostname}.${var.domain}
  restartPolicy: always

