kind: Deploy
apiVersion: garden.io/v2
name: mcpo
description: MCP Orchestrator
type: container

spec:
  image: ghcr.io/open-webui/mcpo:main
  env:
    MCPO_API_KEY: ${var.MCPO_API_KEY}
  ports:
    - name: http
      containerPort: 8000
  volumes:
    - name: config
      containerPath: /app/config/mcp_servers.json
      sourcePath: ${var.config-path}/mcpo/mcp_servers.json
  command: [--api-key, "${var.MCPO_API_KEY}", --host, 0.0.0.0, --port, 8000, --cors-allow-origins, "*", --config, /app/config/mcp_servers.json]
  ingresses:
    - path: /
      port: http
      hostname: mcpo.${var.domain}
  healthCheck:
    httpGet:
      path: /openapi.json
      port: http
  restartPolicy: always
