kind: Build
apiVersion: garden.io/v2
name: firecrawl-api
description: Firecrawl API service
type: container
source:
  repository:
    url: "git+https://github.com/firecrawl/firecrawl.git#main:/apps/api"

---
kind: Deploy
apiVersion: garden.io/v2
name: firecrawl-api
description: Firecrawl API container
type: container
dependencies:
  - build.firecrawl-api
  - deploy.redis
  - deploy.playwright-service
  - deploy.nuq-postgres

spec:
  image: ${actions.build.firecrawl-api.outputs.deploymentImageId}
  env:
    REDIS_URL: ${var.REDIS_HOST || "redis://redis:6379"}
    REDIS_RATE_LIMIT_URL: ${var.REDIS_HOST || "redis://redis:6379"}
    PLAYWRIGHT_MICROSERVICE_URL: ${var.PLAYWRIGHT_HOST || "http://playwright-service:3000"}/scrape
    NUQ_DATABASE_URL: ${var.FIRECRAWL_NUQ_DATABASE_URL || "postgres://postgres:postgres@nuq-postgres:5432/postgres"}
    USE_DB_AUTHENTICATION: ${var.FIRECRAWL_USE_DB_AUTHENTICATION || "false"}
    OLLAMA_BASE_URL: ${var.FIRECRAWL_OLLAMA_BASE_URL || ""}
    SLACK_WEBHOOK_URL: ${var.SLACK_WEBHOOK_URL || ""}
    BULL_AUTH_KEY: ${var.FIRECRAWL_BULL_AUTH_KEY}
    TEST_API_KEY: ${var.FIRECRAWL_TEST_API_KEY}
    POSTHOG_API_KEY: ${var.POSTHOG_API_KEY || ""}
    POSTHOG_HOST: ${var.POSTHOG_HOST || ""}
    SUPABASE_ANON_TOKEN: ${var.FIRECRAWL_SUPABASE_ANON_TOKEN || ""}
    SUPABASE_URL: ${var.FIRECRAWL_SUPABASE_URL || ""}
    SUPABASE_SERVICE_TOKEN: ${var.FIRECRAWL_SUPABASE_SERVICE_TOKEN || ""}
    SELF_HOSTED_WEBHOOK_URL: ${var.FIRECRAWL_SELF_HOSTED_WEBHOOK_URL || ""}
    SERPER_API_KEY: ${var.FIRECRAWL_SERPER_API_KEY || ""}
    SEARCHAPI_API_KEY: ${var.FIRECRAWL_SEARCHAPI_API_KEY || ""}
    SEARXNG_ENDPOINT: ${var.FIRECRAWL_SEARXNG_ENDPOINT || "https://searxng.bolabaden.org"}
    HOST: 0.0.0.0
    PORT: ${var.FIRECRAWL_INTERNAL_PORT || "3002"}
    WORKER_PORT: ${var.FIRECRAWL_WORKER_PORT || "3005"}
    ENV: ${var.FIRECRAWL_ENV || "local"}
  ports:
    - name: http
      containerPort: 3002
  resources:
    limits:
      cpu: 4000m
      memory: 4Gi
    requests:
      memory: 4G
  ingresses:
    - path: /
      port: http
      hostname: firecrawl-api.${var.domain}
  restartPolicy: always
