kind: Build
apiVersion: garden.io/v0
name: nuq-postgres
description: PostgreSQL database for Firecrawl
type: container
source:
  repository:
    url: "git+https://github.com/firecrawl/firecrawl.git#main:/apps/nuq-postgres"

---
kind: Deploy
apiVersion: garden.io/v0
name: nuq-postgres
description: PostgreSQL database container
type: container
dependencies:
  - build.nuq-postgres

spec:
  replicas: 3
  image: ${actions.build.nuq-postgres.outputs.deploymentImageId}
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    POSTGRES_USER: ${var.FIRECRAWL_POSTGRES_USER || "postgres"}
    POSTGRES_PASSWORD: ${var.FIRECRAWL_POSTGRES_PASSWORD || "postgres"}
    POSTGRES_DB: ${var.FIRECRAWL_POSTGRES_DB || "postgres"}
  ports:
    - name: db
      containerPort: 5432
  volumes:
    - name: data
      containerPath: /var/lib/postgresql/data
      sourcePath: ${var.config-path}/nuq-postgres/data
  healthCheck:
    exec:
      command:
        - sh
        - -c
        - 'pg_isready -U ${var.FIRECRAWL_POSTGRES_USER || "postgres"} -d ${var.FIRECRAWL_POSTGRES_DB || "postgres"}'
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
  restartPolicy: always
