kind: Build
apiVersion: garden.io/v2
name: nuq-postgres
description: PostgreSQL database for Firecrawl
type: container
source:
  repository:
    url: "git+https://github.com/firecrawl/firecrawl.git#main:/apps/nuq-postgres"

---
kind: Deploy
apiVersion: garden.io/v2
name: nuq-postgres
description: PostgreSQL database container
type: container
dependencies:
  - build.nuq-postgres

spec:
  image: ${actions.build.nuq-postgres.outputs.deploymentImageId}
  env:
    POSTGRES_USER: ${var.FIRECRAWL_POSTGRES_USER || "postgres"}
    POSTGRES_PASSWORD: ${var.FIRECRAWL_POSTGRES_PASSWORD || "postgres"}
    POSTGRES_DB: ${var.FIRECRAWL_POSTGRES_DB || "postgres"}
  ports:
    - name: db
      containerPort: 5432
  healthCheck:
    exec:
      command:
        - pg_isready
        - -U
        - ${var.FIRECRAWL_POSTGRES_USER || "postgres"}
        - -d
        - ${var.FIRECRAWL_POSTGRES_DB || "postgres"}
  restartPolicy: Always
