
x-common-env: &common-env
  TZ: ${TZ:-America/Chicago} # Your Timezone
  PUID: ${PUID:-1002}
  PGID: ${PGID:-988}
  UMASK: ${UMASK:-002}

x-common-uidgid: &common-uidgid
  user: ${PUID:-1002}:${PGID:-988}

x-resource-limits: &resource-limits
  cpu_shares: 1024
  labels:
    autoheal: "true"

x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
  labels:
    autoheal: "true"
    swarm.autoscaler: "true"

x-swarm-resource-limits: &swarm-resource-limits
  resources:
    limits:
      cpus: "0.10"
      memory: 512M

x-swarm-preferences-worker-priority: &swarm-preferences-worker-priority
  placement:
    preferences:
      - spread: node.labels.worker_priority

x-swarm-constraints-worker-only: &swarm-constraints-worker-only
  placement:
    constraints:
      - node.role == worker

x-swarm-constraints-manager-only: &swarm-constraints-manager-only
  placement:
    constraints:
      - node.role == manager

x-jellyfin-labels: &jellyfin-labels
  traefik.enable: "true"
  traefik.http.services.jellyfin.loadbalancer.server.port: 8096

x-jellystat-labels: &jellystat-labels
  traefik.enable: "true"
  traefik.http.services.jellystat.loadbalancer.server.port: 3000

services:
  channels-dvr:
    # 🔹🔹 Channels DVR 🔹🔹    # https://github.com/fancybits/channels-dvr
    # todo: docs
    image: fancybits/channels-dvr
    # Use the fancybits/channels-dvr:tve image if you need TV Everywhere support
    container_name: channels-dvr
    hostname: channels-dvr
    networks:
      - infranet
    ports:
      - ${CHANNELS_DVR_PORT:-8089}:8089
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${CONFIG_PATH:-./volumes}/channels-dvr/config:/channels-dvr
      - ${DATA_PATH:-./data}/media/dvr/recordings:/shares/DVR
    restart: always

  jellyfin:
    # 🔹🔹 Jellyfin 🔹🔹
    image: linuxserver/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    networks:
      - traefik_public
    ports:
      - ${JELLYFIN_PORT:-8096}:8096
      - ${JELLYFIN_PORT2:-8920}:8920
      - ${JELLYFIN_DLNA_PORT:-1901}:1900/udp
      - ${JELLYFIN_PORT3:-7359}:7359/udp
    volumes:
      - ${DATA_DIR:-./data}/media/anime:/media/anime
      - ${DATA_DIR:-./data}/media/books:/media/books
      - ${DATA_DIR:-./data}/media/comics:/media/comics
      - ${DATA_DIR:-./data}/media/manga:/media/manga
      - ${DATA_DIR:-./data}/media/movies:/media/movies
      - ${DATA_DIR:-./data}/media/music:/media/music
      - ${DATA_DIR:-./data}/media/music/videos:/media/music/videos
      - ${DATA_DIR:-./data}/media/tv:/media/tv
      - ${DATA_DIR:-./data}/media/xxx:/media/xxx
      - ${CONFIG_PATH:-./volumes}/jellyfin/data:/data
      - ${CONFIG_PATH:-./volumes}/jellyfin/cache:/cache
      - ${CONFIG_PATH:-./volumes}/jellyfin/config:/config
      - ${CONFIG_PATH:-./volumes}/jellyfin/transcode:/transcode
    environment:
      <<: *common-env
      JELLYFIN_PublishedServerUrl: https://jellyfin.$DOMAIN
    labels:
      <<: *jellyfin-labels
      homepage.group: Media Streaming
      homepage.name: Jellyfin Media Server
      homepage.icon: jellyfin.png
      homepage.href: https://jellyfin.$DOMAIN/
      homepage.description: Organize and stream your movies, TV shows, and music to any device, creating your own personal media center.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *jellyfin-labels
    restart: always

  jellystat:
    # 🔹🔹 Jellystat 🔹🔹
    depends_on:
      postgresql:
        condition: service_healthy
    image: cyfershepard/jellystat
    container_name: jellystat
    hostname: jellystat
    networks:
      - infranet
      - traefik_public
    ports:
      - ${JELLYSTAT_PORT:-3003}:3000
    volumes:
      - ${CONFIG_PATH:-./volumes}/jellystat/backup-data:/app/backend/backup-data
    environment:
      <<: *common-env
      POSTGRES_USER: ${JELLYSTAT_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: $JELLYSTAT_POSTGRES_PASSWORD
      POSTGRES_IP: ${JELLYSTAT_POSTGRES_IP:-postgresql}
      POSTGRES_PORT: ${JELLYSTAT_POSTGRES_PORT:-5432}
      JWT_SECRET_FILE: /run/secrets/jellystat_jwt_secret
    labels:
      <<: *jellystat-labels
      homepage.group: Media Statistics
      homepage.name: Jellystat Analytics
      homepage.icon: jellystat.png
      homepage.href: https://jellystat.$DOMAIN
      homepage.description: Tracks and displays statistics about your Jellyfin media server usage, showing you what's being watched and how often.
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *jellystat-labels
    secrets:
      - jellystat_jwt_secret
    restart: always

secrets:
  jellystat_jwt_secret:
    file: ${SECRETS_DIR:-./secrets}/jellystat_jwt_secret

# to build the secrets:
# openssl rand -base64 32 > ${SECRETS_DIR:-./secrets}/jellystat_postgres_password
# openssl rand -base64 32 > ${SECRETS_DIR:-./secrets}/jellystat_jwt_secret
