x-common-env: &common-env
  TZ: ${TZ:-America/Chicago} # Your Timezone
  PUID: ${PUID:-1002}
  PGID: ${PGID:-988}
  UMASK: ${UMASK:-002}

x-common-uidgid: &common-uidgid
  user: ${PUID:-1002}:${PGID:-988}

x-resource-limits: &resource-limits
  cpu_shares: 1024
  labels:
    autoheal: "true"

x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
  labels:
    autoheal: "true"
    swarm.autoscaler: "true"

x-swarm-resource-limits: &swarm-resource-limits
  resources:
    limits:
      cpus: "0.10"
      memory: 512M

x-swarm-preferences-worker-priority: &swarm-preferences-worker-priority
  placement:
    preferences:
      - spread: node.labels.worker_priority

x-swarm-constraints-worker-only: &swarm-constraints-worker-only
  placement:
    constraints:
      - node.role == worker

x-swarm-constraints-manager-only: &swarm-constraints-manager-only
  placement:
    constraints:
      - node.role == manager

x-google-forward-auth-env: &google-forward-auth-env
  AUTH_HOST: "google-forward-auth.$DOMAIN"
  CLIENT_ID: "$PROVIDERS_GOOGLE_CLIENT_ID"
  CLIENT_SECRET: "$PROVIDERS_GOOGLE_CLIENT_SECRET"
  COOKIE_DOMAIN: "$DOMAIN"
  COOKIE_SECRET: "$PROVIDERS_GOOGLE_COOKIE_SECRET"
  DEFAULT_ACTION: ${GOOGLE_FORWARD_AUTH_DEFAULT_ACTION:-auth}
  DEFAULT_PROVIDER: ${GOOGLE_FORWARD_AUTH_DEFAULT_PROVIDER:-google}
  EMAIL_DOMAINS: "*"
  HTTP_ADDRESS: "0.0.0.0:${GOOGLE_FORWARD_AUTH_PORT:-4180}"
  INSECURE_COOKIE: ${GOOGLE_FORWARD_AUTH_INSECURE_COOKIE:-false}
  LIFETIME: ${GOOGLE_FORWARD_AUTH_LIFETIME:-86400} # 1 day
  LOG_FORMAT: ${GOOGLE_FORWARD_AUTH_LOG_FORMAT:-text}
  LOG_LEVEL: ${GOOGLE_FORWARD_AUTH_LOG_LEVEL:-info} # set to trace while testing bypass rules
  OIDC_ISSUER_URL: "${GOOGLE_FORWARD_AUTH_OIDC_ISSUER_URL:-https://accounts.google.com}"
  PROVIDER: "google"
  REDIRECT_URL: "https://google-forward-auth.$DOMAIN/oauth2/callback"
  SECRET: $GOOGLE_FORWARD_AUTH_SECRET
  UPSTREAMS: "static://202"
  URL_PATH: ${GOOGLE_FORWARD_AUTH_URL_PATH:-/_oauth}
  WHITELIST_DOMAINS: "${GOOGLE_FORWARD_AUTH_WHITELIST_DOMAINS:-.google-forward-auth.localhost}" # Required to allow redirection back to original requested target.
  # Mandatory option when using oauth2-proxy with traefik
  REVERSE_PROXY: "${GOOGLE_FORWARD_AUTH_REVERSE_PROXY:-true}"
  # The following option skip the page requesting the user
  # to click on a button to be redirected to the identity provider
  # It can be activated only when traefik is not configure with
  # the error redirection middleware as this example.
  SKIP_PROVIDER_BUTTON: "${GOOGLE_FORWARD_AUTH_SKIP_PROVIDER_BUTTON:-true}"
  # Required for traefik with ForwardAuth and static upstream configuration

services:
  google-oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    container_name: google-oauth2-proxy
    hostname: google-oauth2-proxy
    <<: [*common-uidgid, *common-logging, *resource-limits]
    ports:
      - ${OAUTH2_PROXY_PORT:-4180}:4180/tcp
    environment:
      <<: *common-env
      OAUTH2_PROXY_CLIENT_ID: "$PROVIDERS_GOOGLE_CLIENT_ID"
      OAUTH2_PROXY_CLIENT_SECRET: "$PROVIDERS_GOOGLE_CLIENT_SECRET"
      OAUTH2_PROXY_COOKIE_DOMAIN: "$DOMAIN"
      OAUTH2_PROXY_COOKIE_SECRET: "$PROVIDERS_GOOGLE_COOKIE_SECRET"
      OAUTH2_PROXY_COOKIE_SECURE: ${GOOGLE_OAUTH2_PROXY_COOKIE_SECURE:-false}
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:${GOOGLE_OAUTH2_PROXY_PORT:-4180}"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "${GOOGLE_OAUTH2_PROXY_OIDC_ISSUER_URL:-https://accounts.google.com}"
      OAUTH2_PROXY_PROVIDER: "google"
      OAUTH2_PROXY_REDIRECT_URL: "https://$DOMAIN/oauth2/callback"
      # Mandatory option when using oauth2-proxy with traefik
      OAUTH2_PROXY_REVERSE_PROXY: ${GOOGLE_OAUTH2_PROXY_REVERSE_PROXY:-true}
      # The following option skip the page requesting the user
      # to click on a button to be redirected to the identity provider
      # It can be activated only when traefik is not configure with
      # the error redirection middleware as this example.
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: ${GOOGLE_OAUTH2_PROXY_SKIP_PROVIDER_BUTTON:-true}
      # Required for traefik with ForwardAuth and static upstream configuration 
      OAUTH2_PROXY_UPSTREAMS: "static://202"
      OAUTH2_PROXY_WHITELIST_DOMAINS: "${GOOGLE_OAUTH2_PROXY_WHITELIST_DOMAINS:-.oauth2-proxy.localhost}"  # Required to allow redirection back to original requested target.
    labels:
      traefik.enable: "true"
      traefik.http.routers.google-oauth2-proxy.rule: "Host(`google-oauth2.$DOMAIN`)"
      traefik.http.services.google-oauth2-proxy.loadbalancer.server.port: ${GOOGLE_OAUTH2_PROXY_PORT:-4180}
    restart: always
