package main

import (
	"fmt"
)

// defineServicesStremio returns all services from compose/docker-compose.stremio-group.yml
// Note: Some services are profile-based (comet, mediafusion, mediaflow-proxy) and are excluded
func defineServicesStremio(config *Config) []Service {
	domain := config.Domain
	configPath := config.ConfigPath
	secretsPath := config.SecretsPath
	tsHostname := getEnv("TS_HOSTNAME", "localhost")

	services := []Service{}

	// stremio
	services = append(services, Service{
		Name:          "stremio",
		Image:         "ghcr.io/tsaridas/stremio-docker:main",
		ContainerName: "stremio",
		Hostname:      "stremio",
		Networks:      []string{"publicnet", "warp-nat-net"},
		Ports: []PortMapping{
			{HostPort: "11470", ContainerPort: "11470", Protocol: "tcp"},
			{HostPort: "12470", ContainerPort: "12470", Protocol: "tcp"},
		},
		Volumes: []VolumeMount{
			{Source: fmt.Sprintf("%s/stremio/root/.stremio-server", configPath), Target: "/root/.stremio-server", Type: "bind"},
		},
		Environment: map[string]string{
			"IPADDRESS":        "127.0.0.1",
			"AUTO_SERVER_URL":  "1",
			"SERVER_URL":       fmt.Sprintf("https://stremio.%s/", domain),
			"WEBUI_LOCATION":   fmt.Sprintf("https://stremio.%s/shell/", domain),
			"NO_CORS":          "0",
			"CASTING_DISABLED": "1",
		},
		Labels: map[string]string{
			"deunhealth.restart.on.unhealthy": "true",
			"traefik.enable":                  "true",
			"traefik.http.middlewares.stremio-web-redirect.redirectRegex.regex":                    fmt.Sprintf("^(http|https)://stremio(-web)\\.(%s|%s\\.%s)(.*)$", domain, tsHostname, domain),
			"traefik.http.middlewares.stremio-web-redirect.redirectRegex.replacement":              "$1://stremio.$3$4",
			"traefik.http.middlewares.stremio-web-redirect.redirectRegex.permanent":                "false",
			"traefik.http.middlewares.stremio-shell-redirect.redirectRegex.regex":                  fmt.Sprintf("^(http|https)://stremio\\.(%s|%s\\.%s)(.*)$", domain, tsHostname, domain),
			"traefik.http.middlewares.stremio-shell-redirect.redirectRegex.replacement":            "$1://stremio.$2$3",
			"traefik.http.middlewares.stremio-shell-redirect.redirectRegex.permanent":              "false",
			"traefik.http.middlewares.stremio-streaming-server-redirect.redirectRegex.regex":       fmt.Sprintf("^(http|https)://stremio\\.(%s|%s\\.%s)(/shell[^#?]*)(\\\\?[^#]*?streamingServer=[^&#]*)?([^#]*)(#.*)?$", domain, tsHostname, domain),
			"traefik.http.middlewares.stremio-streaming-server-redirect.redirectRegex.replacement": "$1://stremio.$2$3?streamingServer=https%3A%2F%2Fstremio.$2$5$6",
			"traefik.http.middlewares.stremio-streaming-server-redirect.redirectRegex.permanent":   "false",
			"traefik.http.routers.stremio.service":                                                 "stremio",
			"traefik.http.routers.stremio.rule":                                                    fmt.Sprintf("Host(`stremio-web.%s`) || Host(`stremio-web.%s.%s`) || Host(`stremio.%s`) || Host(`stremio.%s.%s`)", domain, tsHostname, domain, domain, tsHostname, domain),
			"traefik.http.routers.stremio.middlewares":                                             "stremio-web-redirect@docker,stremio-shell-redirect@docker,stremio-streaming-server-redirect@docker",
			"traefik.http.services.stremio.loadbalancer.server.scheme":                             "https",
			"traefik.http.services.stremio.loadbalancer.server.port":                               "8080",
			"traefik.http.routers.stremio-http11470.service":                                       "stremio-http11470",
			"traefik.http.services.stremio-http11470.loadbalancer.server.scheme":                   "http",
			"traefik.http.services.stremio-http11470.loadbalancer.server.port":                     "11470",
			"traefik.http.routers.stremio-http11470.rule":                                          fmt.Sprintf("(Host(`stremio.%s`) || Host(`stremio.%s.%s`)) && ( PathPrefix(`/hlsv2`) || PathPrefix(`/casting`) || PathPrefix(`/local-addon`) || PathPrefix(`/proxy`) || PathPrefix(`/rar`) || PathPrefix(`/zip`) || PathPrefix(`/settings`) || PathPrefix(`/create`) || PathPrefix(`/removeAll`) || PathPrefix(`/samples`) || PathPrefix(`/probe`) || PathPrefix(`/subtitlesTracks`) || PathPrefix(`/opensubHash`) || PathPrefix(`/subtitles`) || PathPrefix(`/network-info`) || PathPrefix(`/device-info`) || PathPrefix(`/get-https`) || PathPrefix(`/hwaccel-profiler`) || PathPrefix(`/status`) || PathPrefix(`/exec`) || PathPrefix(`/stream`) || PathRegexp(`^/[^/]+/(stats\\.json|create|remove|destroy)$`) || PathRegexp(`^/[^/]+/[^/]+/(stats\\.json|hls\\.m3u8|master\\.m3u8|stream\\.m3u8|dlna|thumb\\.jpg)$`) || PathRegexp(`^/[^/]+/[^/]+/(stream-q-[^/]+\\.m3u8|stream-[^/]+\\.m3u8|subs-[^/]+\\.m3u8)$`) || PathRegexp(`^/[^/]+/[^/]+/(stream-q-[^/]+|stream-[^/]+)/[^/]+\\.(ts|mp4)$`) || PathRegexp(`^/yt/[^/]+(\\.json)?$`) || Path(`/thumb.jpg`) || Path(`/stats.json`) )", domain, tsHostname, domain),
			"traefik.http.routers.stremio-https12470.service":                                      "stremio-https12470",
			"traefik.http.services.stremio-https12470.loadbalancer.server.scheme":                  "https",
			"traefik.http.services.stremio-https12470.loadbalancer.server.port":                    "12470",
			"traefik.http.routers.stremio-https12470.rule":                                         fmt.Sprintf("(Host(`stremio.%s`) || Host(`stremio.%s.%s`)) && ( PathPrefix(`/hlsv2`) || PathPrefix(`/casting`) || PathPrefix(`/local-addon`) || PathPrefix(`/proxy`) || PathPrefix(`/rar`) || PathPrefix(`/zip`) || PathPrefix(`/settings`) || PathPrefix(`/create`) || PathPrefix(`/removeAll`) || PathPrefix(`/samples`) || PathPrefix(`/probe`) || PathPrefix(`/subtitlesTracks`) || PathPrefix(`/opensubHash`) || PathPrefix(`/subtitles`) || PathPrefix(`/network-info`) || PathPrefix(`/device-info`) || PathPrefix(`/get-https`) || PathPrefix(`/hwaccel-profiler`) || PathPrefix(`/status`) || PathPrefix(`/exec`) || PathPrefix(`/stream`) || PathRegexp(`^/[^/]+/(stats\\.json|create|remove|destroy)$`) || PathRegexp(`^/[^/]+/[^/]+/(stats\\.json|hls\\.m3u8|master\\.m3u8|stream\\.m3u8|dlna|thumb\\.jpg)$`) || PathRegexp(`^/[^/]+/[^/]+/(stream-q-[^/]+\\.m3u8|stream-[^/]+\\.m3u8|subs-[^/]+\\.m3u8)$`) || PathRegexp(`^/[^/]+/[^/]+/(stream-q-[^/]+|stream-[^/]+)/[^/]+\\.(ts|mp4)$`) || PathRegexp(`^/yt/[^/]+(\\.json)?$`) || Path(`/thumb.jpg`) || Path(`/stats.json`) )", domain, tsHostname, domain),
			"homepage.group":             "Media Streaming Platforms",
			"homepage.name":              "Stremio",
			"homepage.icon":              "stremio.png",
			"homepage.href":              fmt.Sprintf("https://stremio.%s/", domain),
			"homepage.description":       "A one-stop hub for video content aggregation, allowing you to stream movies, series, and more from various sources.",
			"kuma.stremio.http.name":     fmt.Sprintf("stremio.%s.%s", tsHostname, domain),
			"kuma.stremio.http.url":      fmt.Sprintf("https://stremio.%s", domain),
			"kuma.stremio.http.interval": "60",
		},
		Healthcheck: &Healthcheck{
			Test:        []string{"CMD-SHELL", "command -v curl >/dev/null || (apk add --no-cache curl >/dev/null 2>&1 || apt-get update >/dev/null 2>&1 && apt-get install -y curl >/dev/null 2>&1); (curl -fs http://127.0.0.1:11470/ >/dev/null 2>&1 || curl -fsk https://127.0.0.1:12470/ >/dev/null 2>&1) || exit 1"},
			Interval:    "30s",
			Timeout:     "10s",
			Retries:     3,
			StartPeriod: "90s",
		},
		CPUs:           "2",
		MemLimit:       "2G",
		MemReservation: "256M",
		Restart:        "always",
	})

	// flaresolverr
	flaresolverrPort := getEnv("FLARESOLVERR_PORT", "8191")
	services = append(services, Service{
		Name:          "flaresolverr",
		Image:         "ghcr.io/flaresolverr/flaresolverr",
		ContainerName: "flaresolverr",
		Hostname:      "flaresolverr",
		Networks:      []string{"backend", "publicnet"},
		Environment: map[string]string{
			"TZ":                 getEnv("TZ", "America/Chicago"),
			"PUID":               getEnv("PUID", "1001"),
			"PGID":               getEnv("PGID", "988"),
			"UMASK":              getEnv("UMASK", "002"),
			"LOG_LEVEL":          "debug",
			"LOG_HTML":           "false",
			"CAPTCHA_SOLVER":     "none",
			"PORT":               flaresolverrPort,
			"HOST":               "0.0.0.0",
			"HEADLESS":           getEnv("FLARESOLVERR_HEADLESS", "true"),
			"BROWSER_TIMEOUT":    getEnv("FLARESOLVERR_BROWSER_TIMEOUT", "120000"),
			"TEST_URL":           getEnv("FLARESOLVERR_TEST_URL", "https://www.google.com"),
			"PROMETHEUS_ENABLED": getEnv("FLARESOLVERR_PROMETHEUS_ENABLED", "true"),
			"PROMETHEUS_PORT":    getEnv("PROMETHEUS_PORT", "9090"),
		},
		Labels: map[string]string{
			"deunhealth.restart.on.unhealthy":                             "true",
			"traefik.enable":                                              "true",
			"traefik.http.routers.flaresolverr.middlewares":               "nginx-auth@file",
			"traefik.http.routers.flaresolverr.rule":                      fmt.Sprintf("Host(`flaresolverr.%s`) || Host(`flaresolverr.%s.%s`)", domain, tsHostname, domain),
			"traefik.http.services.flaresolverr.loadbalancer.server.port": flaresolverrPort,
			"homepage.group":                                              "Infrastructure",
			"homepage.name":                                               "Flaresolverr",
			"homepage.icon":                                               "flaresolverr.png",
			"homepage.href":                                               fmt.Sprintf("https://flaresolverr.%s/", domain),
			"homepage.description":                                        "Headless anti-bot proxy to bypass Cloudflare/JS challenges for indexers and scrapers",
			"kuma.flaresolverr.http.name":                                 fmt.Sprintf("flaresolverr.%s.%s", tsHostname, domain),
			"kuma.flaresolverr.http.url":                                  fmt.Sprintf("https://flaresolverr.%s", domain),
			"kuma.flaresolverr.http.interval":                             "30",
		},
		Healthcheck: &Healthcheck{
			Test:        []string{"CMD-SHELL", fmt.Sprintf("curl -f http://127.0.0.1:%s/health > /dev/null 2>&1 || exit 1", flaresolverrPort)},
			Interval:    "30s",
			Timeout:     "15s",
			Retries:     3,
			StartPeriod: "60s",
		},
		CPUs:           "0.6",
		MemLimit:       "1G",
		MemReservation: "64M",
		Restart:        "always",
		ExtraHosts:     []string{"host.docker.internal:host-gateway"},
	})

	// jackett
	services = append(services, Service{
		Name:          "jackett",
		Image:         "lscr.io/linuxserver/jackett",
		ContainerName: "jackett",
		Hostname:      "jackett",
		Networks:      []string{"publicnet", "warp-nat-net"},
		Configs: []ConfigMount{
			{Source: fmt.Sprintf("%s/stremio/jackett-serverconfig.json", configPath), Target: "/defaults/ServerConfig.json", Mode: "0644"},
			{Source: fmt.Sprintf("%s/stremio/jackett-indexer-blacklist.txt", configPath), Target: "/indexer-blacklist.txt", Mode: "0644"},
			{Source: fmt.Sprintf("%s/stremio/jackett-init.sh", configPath), Target: "/custom-cont-init.d/99-remove-slow-indexers", Mode: "0755"},
		},
		Volumes: []VolumeMount{
			{Source: fmt.Sprintf("%s/jackett/config", configPath), Target: "/config", Type: "bind"},
			{Source: "/mnt/remote/blackhole", Target: "/blackhole", Type: "bind"},
		},
		Environment: map[string]string{
			"TZ":              getEnv("TZ", "America/Chicago"),
			"PUID":            getEnv("PUID", "1001"),
			"PGID":            getEnv("PGID", "988"),
			"UMASK":           getEnv("UMASK", "002"),
			"AUTO_UPDATE":     getEnv("JACKETT_AUTO_UPDATE", "true"),
			"RUN_OPTS":        getEnv("JACKETT_RUN_OPTS", ""),
			"JACKETT_API_KEY": getEnv("JACKETT_API_KEY", ""),
		},
		Labels: map[string]string{
			"deunhealth.restart.on.unhealthy":                        "true",
			"traefik.enable":                                         "true",
			"traefik.http.routers.jackett.rule":                      fmt.Sprintf("Host(`jackett.%s`) || Host(`jackett.%s.%s`)", domain, tsHostname, domain),
			"traefik.http.services.jackett.loadbalancer.server.port": "9117",
			"kuma.jackett.http.name":                                 fmt.Sprintf("jackett.%s.%s", tsHostname, domain),
			"kuma.jackett.http.url":                                  fmt.Sprintf("https://jackett.%s/api/v2.0/indexers/all/results/torznab?t=indexers&apikey=$JACKETT_API_KEY", domain),
			"kuma.jackett.http.interval":                             "30",
		},
		Healthcheck: &Healthcheck{
			Test:        []string{"CMD-SHELL", "curl -fs http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab?t=indexers&apikey=$JACKETT_API_KEY > /dev/null 2>&1 || exit 1"},
			Interval:    "30s",
			Timeout:     "10s",
			StartPeriod: "60s",
		},
		CPUs:           "1",
		MemLimit:       "1024M",
		MemReservation: "128M",
		DependsOn:      []string{"flaresolverr"},
		Restart:        "always",
		ExtraHosts:     []string{"host.docker.internal:host-gateway"},
	})

	// prowlarr
	services = append(services, Service{
		Name:          "prowlarr",
		Image:         "lscr.io/linuxserver/prowlarr",
		ContainerName: "prowlarr",
		Hostname:      "prowlarr",
		Networks:      []string{"publicnet", "warp-nat-net"},
		Ports: []PortMapping{
			{HostIP: "127.0.0.1", HostPort: "9696", ContainerPort: "9696", Protocol: "tcp"},
		},
		Volumes: []VolumeMount{
			{Source: fmt.Sprintf("%s/prowlarr/config", configPath), Target: "/config", Type: "bind"},
		},
		Environment: map[string]string{
			"TZ":   getEnv("TZ", "America/Chicago"),
			"PUID": getEnv("PUID", "1001"),
			"PGID": getEnv("PGID", "988"),
		},
		Labels: map[string]string{
			"deunhealth.restart.on.unhealthy":                         "true",
			"traefik.enable":                                          "true",
			"traefik.http.routers.prowlarr.rule":                      fmt.Sprintf("Host(`prowlarr.%s`) || Host(`prowlarr.%s.%s`)", domain, tsHostname, domain),
			"traefik.http.services.prowlarr.loadbalancer.server.port": "9696",
			"kuma.prowlarr.http.name":                                 fmt.Sprintf("prowlarr.%s.%s", tsHostname, domain),
			"kuma.prowlarr.http.url":                                  fmt.Sprintf("https://prowlarr.%s/api/v1/system/status", domain),
			"kuma.prowlarr.http.interval":                             "60",
		},
		Healthcheck: &Healthcheck{
			Test:        []string{"CMD-SHELL", fmt.Sprintf("curl -fs -H \"Authorization: Bearer ${PROWLARR_API_KEY:?}\" http://127.0.0.1:9696/api/v1/system/status || exit 1")},
			Interval:    "30s",
			Timeout:     "10s",
			Retries:     3,
			StartPeriod: "120s",
		},
		MemLimit:       "6G",
		MemReservation: "128M",
		CPUs:           "2.0",
		Restart:        "always",
		ExtraHosts:     []string{"host.docker.internal:host-gateway"},
	})

	// aiostreams
	aiostreamsPort := getEnv("AIOSTREAMS_PORT", "3000")
	services = append(services, Service{
		Name:          "aiostreams",
		Image:         "ghcr.io/viren070/aiostreams",
		ContainerName: "aiostreams",
		Hostname:      "aiostreams",
		Networks:      []string{"publicnet", "warp-nat-net"},
		Secrets: []SecretMount{
			{Source: fmt.Sprintf("%s/aiostreams-secret-key.txt", secretsPath), Target: "/run/secrets/aiostreams-secret-key", Mode: "0400"},
			{Source: fmt.Sprintf("%s/aiostreams-addon-password.txt", secretsPath), Target: "/run/secrets/aiostreams-addon-password", Mode: "0400"},
			{Source: fmt.Sprintf("%s/tmdb-access-token.txt", secretsPath), Target: "/run/secrets/tmdb-access-token", Mode: "0400"},
			{Source: fmt.Sprintf("%s/tmdb-api-key.txt", secretsPath), Target: "/run/secrets/tmdb-api-key", Mode: "0400"},
			{Source: fmt.Sprintf("%s/realdebrid-api-key.txt", secretsPath), Target: "/run/secrets/realdebrid-api-key", Mode: "0400"},
			{Source: fmt.Sprintf("%s/alldebrid-api-key.txt", secretsPath), Target: "/run/secrets/alldebrid-api-key", Mode: "0400"},
			{Source: fmt.Sprintf("%s/premiumize-api-key.txt", secretsPath), Target: "/run/secrets/premiumize-api-key", Mode: "0400"},
			{Source: fmt.Sprintf("%s/debridlink-api-key.txt", secretsPath), Target: "/run/secrets/debridlink-api-key", Mode: "0400"},
			{Source: fmt.Sprintf("%s/torbox-api-key.txt", secretsPath), Target: "/run/secrets/torbox-api-key", Mode: "0400"},
			{Source: fmt.Sprintf("%s/offcloud-api-key.txt", secretsPath), Target: "/run/secrets/offcloud-api-key", Mode: "0400"},
			{Source: fmt.Sprintf("%s/offcloud-password.txt", secretsPath), Target: "/run/secrets/offcloud-password", Mode: "0400"},
		},
		Volumes: []VolumeMount{
			{Source: fmt.Sprintf("%s/stremio/addons/aiostreams/data", configPath), Target: "/app/data", Type: "bind"},
		},
		Environment: map[string]string{
			"TZ":                              getEnv("TZ", "America/Chicago"),
			"PUID":                            getEnv("PUID", "1001"),
			"PGID":                            getEnv("PGID", "988"),
			"UMASK":                           getEnv("UMASK", "002"),
			"ADDON_NAME":                      getEnv("AIOSTREAMS_ADDON_NAME", "BadenAIO"),
			"ADDON_ID":                        fmt.Sprintf("aiostreams.%s", domain),
			"PORT":                            aiostreamsPort,
			"BASE_URL":                        fmt.Sprintf("https://aiostreams.%s", domain),
			"SECRET_KEY":                      getEnv("AIOSTREAMS_SECRET_KEY", ""),
			"ADDON_PASSWORD":                  getEnv("AIOSTREAMS_ADDON_PASSWORD", ""),
			"DATABASE_URI":                    "sqlite://./data/db.sqlite",
			"TMDB_ACCESS_TOKEN_FILE":          "/run/secrets/tmdb-access-token",
			"TMDB_API_KEY_FILE":               "/run/secrets/tmdb-api-key",
			"DEFAULT_REALDEBRID_API_KEY_FILE": "/run/secrets/realdebrid-api-key",
			"DEFAULT_ALLDEBRID_API_KEY_FILE":  "/run/secrets/alldebrid-api-key",
			"DEFAULT_PREMIUMIZE_API_KEY_FILE": "/run/secrets/premiumize-api-key",
			"DEFAULT_DEBRIDLINK_API_KEY_FILE": "/run/secrets/debridlink-api-key",
			"DEFAULT_TORBOX_API_KEY_FILE":     "/run/secrets/torbox-api-key",
			"DEFAULT_OFFCLOUD_API_KEY_FILE":   "/run/secrets/offcloud-api-key",
			"DEFAULT_OFFCLOUD_PASSWORD_FILE":  "/run/secrets/offcloud-password",
		},
		Labels: map[string]string{
			"deunhealth.restart.on.unhealthy":                           "true",
			"traefik.enable":                                            "true",
			"traefik.http.routers.aiostreams.rule":                      fmt.Sprintf("Host(`aiostreams.%s`) || Host(`aiostreams.%s.%s`)", domain, tsHostname, domain),
			"traefik.http.services.aiostreams.loadbalancer.server.port": aiostreamsPort,
			"homepage.group":                                            "Stremio Addons",
			"homepage.name":                                             "AIOStreams",
			"homepage.icon":                                             "aiostreams.png",
			"homepage.href":                                             fmt.Sprintf("https://aiostreams.%s/", domain),
			"homepage.description":                                      "Stremio add-on that aggregates multiple sources into a single unified stream catalog",
			"kuma.aiostreams.http.name":                                 fmt.Sprintf("aiostreams.%s.%s", tsHostname, domain),
			"kuma.aiostreams.http.url":                                  fmt.Sprintf("https://aiostreams.%s", domain),
			"kuma.aiostreams.http.interval":                             "60",
		},
		CPUs:           "1",
		MemLimit:       "1024M",
		MemReservation: "50M",
		Restart:        "always",
	})

	// stremthru
	services = append(services, Service{
		Name:          "stremthru",
		Image:         "docker.io/muniftanjim/stremthru",
		ContainerName: "stremthru",
		Hostname:      "stremthru",
		Networks:      []string{"publicnet", "warp-nat-net"},
		Secrets: []SecretMount{
			{Source: fmt.Sprintf("%s/stremthru-proxy-auth.txt", secretsPath), Target: "/run/secrets/stremthru-proxy-auth", Mode: "0400"},
			{Source: fmt.Sprintf("%s/stremthru-store-auth.txt", secretsPath), Target: "/run/secrets/stremthru-store-auth", Mode: "0400"},
		},
		Volumes: []VolumeMount{
			{Source: fmt.Sprintf("%s/stremio/addons/stremthru/app/data", configPath), Target: "/app/data", Type: "bind"},
		},
		Environment: map[string]string{
			"TZ":                            getEnv("TZ", "America/Chicago"),
			"PUID":                          getEnv("PUID", "1001"),
			"PGID":                          getEnv("PGID", "988"),
			"UMASK":                         getEnv("UMASK", "002"),
			"STREMTHRU_BASE_URL":            fmt.Sprintf("https://stremthru.%s", domain),
			"STREMTHRU_LOG_LEVEL":           "INFO",
			"STREMTHRU_LOG_FORMAT":          "text",
			"STREMTHRU_PROXY_AUTH_FILE":     "/run/secrets/stremthru-proxy-auth",
			"STREMTHRU_AUTH_ADMIN":          getEnv("MAIN_USERNAME", ""),
			"STREMTHRU_STORE_AUTH_FILE":     "/run/secrets/stremthru-store-auth",
			"STREMTHRU_STORE_CONTENT_PROXY": "*:true,premiumize:false",
			"STREMTHRU_CONTENT_PROXY_CONNECTION_LIMIT":      "*:10",
			"STREMTHRU_INTEGRATION_TRAKT_CLIENT_ID":         getEnv("TRAKT_CLIENT_ID", ""),
			"STREMTHRU_INTEGRATION_TRAKT_CLIENT_SECRET":     getEnv("TRAKT_CLIENT_SECRET", ""),
			"STREMTHRU_INTEGRATION_TRAKT_LIST_STALE_TIME":   "12h",
			"STREMTHRU_INTEGRATION_TMDB_ACCESS_TOKEN":       getEnv("TMDB_ACCESS_TOKEN", ""),
			"STREMTHRU_INTEGRATION_TMDB_LIST_STALE_TIME":    "12h",
			"STREMTHRU_INTEGRATION_MDBLIST_LIST_STALE_TIME": "",
			"STREMTHRU_INTEGRATION_GITHUB_USER":             "th3w1zard1",
			"STREMTHRU_INTEGRATION_GITHUB_TOKEN":            getEnv("GITHUB_TOKEN", ""),
			"STREMTHRU_STREMIO_TORZ_LAZY_PULL":              "true",
			"STREMTHRU_FEATURE":                             "+anime,-stremio_p2p",
			"STREMTHRU_DATABASE_URI":                        getEnv("STREMTHRU_DATABASE_URI", "sqlite://./data/stremthru.db"),
			"STREMTHRU_REDIS_URI":                           getEnv("REDIS_INTERNAL_URL", "redis://redis:6379"),
		},
		Labels: map[string]string{
			"deunhealth.restart.on.unhealthy":                          "true",
			"traefik.enable":                                           "true",
			"traefik.http.routers.stremthru.rule":                      fmt.Sprintf("Host(`stremthru.%s`) || Host(`stremthru.%s.%s`)", domain, tsHostname, domain),
			"traefik.http.services.stremthru.loadbalancer.server.port": "8080",
			"homepage.group":                                           "Stremio Addons",
			"homepage.name":                                            "StremThru",
			"homepage.icon":                                            "stremthru.png",
			"homepage.href":                                            fmt.Sprintf("https://stremthru.%s/", domain),
			"homepage.description":                                     "Tunnel/proxy bridge for Debrid services to unify access of streaming links through a single host.",
			"kuma.stremthru.http.name":                                 fmt.Sprintf("stremthru.%s.%s", tsHostname, domain),
			"kuma.stremthru.http.url":                                  fmt.Sprintf("https://stremthru.%s", domain),
			"kuma.stremthru.http.interval":                             "60",
		},
		Healthcheck: &Healthcheck{
			Test:        []string{"CMD-SHELL", "wget -qO- http://127.0.0.1:8080 > /dev/null 2>&1 || exit 1"},
			Interval:    "1m",
			Timeout:     "5s",
			Retries:     3,
			StartPeriod: "15s",
		},
		DependsOn:  []string{"redis"},
		Restart:    "always",
		ExtraHosts: []string{"host.docker.internal:host-gateway"},
	})

	// rclone
	rclonePort := getEnv("RCLONE_PORT", "5572")
	services = append(services, Service{
		Name:          "rclone",
		Image:         "docker.io/rclone/rclone",
		ContainerName: "rclone",
		Hostname:      "rclone",
		Networks:      []string{"backend", "publicnet"},
		Configs: []ConfigMount{
			{Source: fmt.Sprintf("%s/stremio/rclone.conf", configPath), Target: "/config/rclone/rclone.conf", Mode: "0400"},
			{Source: "/etc/fuse.conf", Target: "/etc/fuse.conf", Mode: "0400"},
		},
		Devices: []string{"/dev/fuse"},
		CapAdd:  []string{"SYS_ADMIN"},
		Volumes: []VolumeMount{
			{Source: "/", Target: "/hostfs", Type: "bind", ReadOnly: false},
			{Source: "/etc/group", Target: "/etc/group", Type: "bind", ReadOnly: true},
			{Source: "/etc/passwd", Target: "/etc/passwd", Type: "bind", ReadOnly: true},
			{Source: "/mnt/remote", Target: "/mnt/remote", Type: "bind", ReadOnly: false},
			{Source: fmt.Sprintf("%s/rclone/.cache", configPath), Target: "/.cache", Type: "bind"},
			{Source: fmt.Sprintf("%s/rclone/config/rclone", configPath), Target: "/config/rclone", Type: "bind"},
			{Source: fmt.Sprintf("%s/rclonefm/js", configPath), Target: "/var/lib/rclonefm/js", Type: "bind"},
		},
		Command: []string{
			"rcd",
			"--rc-web-gui",
			"--rc-web-gui-no-open-browser",
			fmt.Sprintf("--rc-addr=:%s", rclonePort),
			"--log-level=INFO",
			"--rc-no-auth",
			"--config=/config/rclone/rclone.conf",
			"--cache-dir=/.cache/rclone",
		},
		Labels: map[string]string{
			"deunhealth.restart.on.unhealthy":                       "true",
			"traefik.enable":                                        "true",
			"traefik.http.routers.rclone.middlewares":               "nginx-auth@file",
			"traefik.http.routers.rclone.rule":                      fmt.Sprintf("Host(`rclone.%s`) || Host(`rclone.%s.%s`)", domain, tsHostname, domain),
			"traefik.http.services.rclone.loadbalancer.server.port": rclonePort,
			"homepage.group":                                        "Cloud",
			"homepage.name":                                         "Rclone",
			"homepage.icon":                                         "rclone.png",
			"homepage.href":                                         fmt.Sprintf("https://rclone.%s/", domain),
			"homepage.description":                                  "A web interface for Rclone.",
			"homepage.weight":                                       "0",
			"kuma.rclone.http.name":                                 fmt.Sprintf("rclone.%s.%s", tsHostname, domain),
			"kuma.rclone.http.url":                                  fmt.Sprintf("https://rclone.%s", domain),
			"kuma.rclone.http.interval":                             "60",
		},
		Healthcheck: &Healthcheck{
			Test:        []string{"CMD-SHELL", "mountpoint -q /mnt/remote"},
			Interval:    "5s",
			Timeout:     "3s",
			Retries:     2,
			StartPeriod: "15s",
		},
		MemLimit:       "1G",
		MemReservation: "60M",
		CPUs:           "1.0",
		Restart:        "always",
		ExtraHosts:     []string{"host.docker.internal:host-gateway"},
	})

	// rclone-init
	services = append(services, Service{
		Name:          "rclone-init",
		Image:         "ghcr.io/coanghel/rclone-docker-automount/rclone-init",
		ContainerName: "rclone-init",
		Hostname:      "rclone-init",
		Networks:      []string{"backend"},
		Configs: []ConfigMount{
			{Source: fmt.Sprintf("%s/stremio/rclone-mounts.json", configPath), Target: "/app/mounts.json", Mode: "0400"},
		},
		Volumes: []VolumeMount{
			{Source: "/mnt/remote", Target: "/mnt/remote", Type: "bind", ReadOnly: false},
		},
		Environment: map[string]string{
			"RCLONE_USERNAME":    "",
			"RCLONE_PASSWORD":    "",
			"RCLONE_PORT":        rclonePort,
			"RCLONE_CONFIG_PATH": "/config/rclone/rclone.conf",
		},
		Healthcheck: &Healthcheck{
			Test:        []string{"CMD-SHELL", "mountpoint -q /mnt/remote"},
			Interval:    "5s",
			Timeout:     "3s",
			Retries:     2,
			StartPeriod: "15s",
		},
		DependsOn:  []string{"rclone"},
		Restart:    "always",
		ExtraHosts: []string{"host.docker.internal:host-gateway"},
	})

	return services
}
