version: '3.8'

x-common-env: &common-env
  TZ: ${TZ:-America/Chicago}

x-common-uidgid: &common-uidgid
  user: ${PUID:-1002}:${PGID:-988}

x-sso-portal-labels: &sso-portal-labels
  traefik.enable: "true"
  traefik.http.routers.sso-portal.rule: "Host(`login.$DOMAIN`)"
  traefik.http.routers.sso-portal.entrypoints: websecure
  traefik.http.routers.sso-portal.tls: "true"
  traefik.http.routers.sso-portal.tls.certresolver: myresolver
  traefik.http.services.sso-portal.loadbalancer.server.port: 3000

services:
  sso-portal:
    build:
      context: ./sso-portal
      dockerfile: Dockerfile
    container_name: sso-portal
    hostname: sso-portal
    <<: [*common-uidgid, *resource-limits]
    environment:
      <<: *common-env
      # Base Configuration
      NODE_ENV: production
      PORT: 3000
      BASE_URL: "https://login.$DOMAIN"
      SESSION_SECRET: "$SESSION_SECRET"
      COOKIE_DOMAIN: "$DOMAIN"
      
      # OAuth Providers
      # Google
      GOOGLE_CLIENT_ID: "$GOOGLE_CLIENT_ID"
      GOOGLE_CLIENT_SECRET: "$GOOGLE_CLIENT_SECRET"
      
      # Facebook
      FACEBOOK_CLIENT_ID: "$FACEBOOK_CLIENT_ID"
      FACEBOOK_CLIENT_SECRET: "$FACEBOOK_CLIENT_SECRET"
      
      # Apple
      APPLE_CLIENT_ID: "$APPLE_CLIENT_ID"
      APPLE_TEAM_ID: "$APPLE_TEAM_ID"
      APPLE_KEY_ID: "$APPLE_KEY_ID"
      APPLE_PRIVATE_KEY: "$APPLE_PRIVATE_KEY"
      
      # Microsoft
      MICROSOFT_CLIENT_ID: "$MICROSOFT_CLIENT_ID"
      MICROSOFT_CLIENT_SECRET: "$MICROSOFT_CLIENT_SECRET"
      
      # GitHub
      GITHUB_CLIENT_ID: "$GITHUB_CLIENT_ID"
      GITHUB_CLIENT_SECRET: "$GITHUB_CLIENT_SECRET"
      
      # Keycloak Integration
      KEYCLOAK_URL: "https://keycloak.$DOMAIN"
      KEYCLOAK_REALM: "${KEYCLOAK_REALM:-master}"
      KEYCLOAK_CLIENT_ID: "${KEYCLOAK_CLIENT_ID:-sso-portal}"
      KEYCLOAK_CLIENT_SECRET: "$KEYCLOAK_CLIENT_SECRET"
      
      # Redis Session Store
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "$REDIS_PASSWORD"
    networks:
      - traefik_public
      - auth-net
    labels:
      <<: *sso-portal-labels
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: sso-portal-redis
    command: redis-server --requirepass $REDIS_PASSWORD
    <<: [*common-uidgid, *resource-limits]
    networks:
      - auth-net
    volumes:
      - redis_data:/data
    restart: always

networks:
  traefik_public:
    external: true
  auth-net:
    external: true

volumes:
  redis_data: