kind: Deploy
apiVersion: garden.io/v0
name: warp-net-init
description: Initialize warp-nat-net network
type: container

spec:
  replicas: 3
  image: docker:cli
  hostNetwork: true
  volumes:
    - name: docker-sock
      containerPath: /var/run/docker.sock
      hostPath: ${var.docker-socket}
      readOnly: true
  command:
    - sh
    - -c
    - |
      if ! docker network inspect ${var.DOCKER_NETWORK_NAME || "warp-nat-net"} >/dev/null 2>&1; then
        echo "Creating network ${var.DOCKER_NETWORK_NAME || "warp-nat-net"}..."
        docker network create \
          --driver=bridge \
          --attachable \
          -o com.docker.network.bridge.name=br_${var.DOCKER_NETWORK_NAME || "warp-nat-net"} \
          -o com.docker.network.bridge.enable_ip_masquerade=false \
          --subnet=${var.WARP_NAT_NET_SUBNET || "10.0.2.0/24"} \
          --gateway=${var.WARP_NAT_NET_GATEWAY || "10.0.2.1"} \
          ${var.DOCKER_NETWORK_NAME || "warp-nat-net"}
        echo "Network created successfully"
      else
        echo "Network ${var.DOCKER_NETWORK_NAME || "warp-nat-net"} already exists"
      fi
  restartPolicy: never

