# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

x-common-env: &common-env
  TZ: ${TZ:-America/Chicago} # Your Timezone
  PUID: ${PUID:-1002}
  PGID: ${PGID:-988}
  UMASK: ${UMASK:-002}

x-common-uidgid: &common-uidgid
  user: ${PUID:-1002}:${PGID:-988}

x-resource-limits: &resource-limits
  cpu_shares: 1024
  labels:
    autoheal: "true"

x-common-deploy: &common-deploy
  restart_policy:
    condition: on-failure
    delay: 5s
    window: 120s
  labels:
    autoheal: "true"
    swarm.autoscaler: "true"

x-swarm-resource-limits: &swarm-resource-limits
  resources:
    limits:
      cpus: "0.10"
      memory: 512M

x-swarm-worker-priority: &swarm-worker-priority
  placement:
    preferences:
      - spread: node.labels.worker_priority

x-swarm-constraints-worker-only: &swarm-constraints-worker-only
  placement:
    constraints:
      - node.role == worker

x-swarm-constraints-manager-only: &swarm-constraints-manager-only
  placement:
    constraints:
      - node.role == manager

x-browserless-labels: &browserless-labels
  traefik.enable: "true"
  traefik.http.services.browserless.loadbalancer.server.port: 3000

x-speedtest-labels: &speedtest-labels
  traefik.enable: "true"
  traefik.http.services.speedtest.loadbalancer.server.port: 80

services:
  speedtest:
    # 🔹🔹 Speedtest 🔹🔹
    image: linuxserver/speedtest-tracker
    container_name: speedtest
    hostname: speedtest
    <<: *resource-limits
    networks:
      - traefik_public
    ports:
      - ${SPEEDTEST_TRACKER_PORT:-8765}:80
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${CONFIG_PATH:-./volumes}/speedtest-tracker:/config
    environment:
      <<: *common-env
      ADMIN_EMAIL: $SPEEDTEST_TRACKER_ADMIN_EMAIL # Email of the initial admin user. Note: Only effective during initial setup.
      ADMIN_NAME: $SPEEDTEST_TRACKER_ADMIN_NAME # Name of the initial admin user. Note: Only effective during initial setup.
      ADMIN_PASSWORD: $SPEEDTEST_TRACKER_ADMIN_PASSWORD # Password of the initial admin user. Note: Only effective during initial setup.
      API_RATE_LIMIT: ${SPEEDTEST_TRACKER_API_RATE_LIMIT:-60} # Number of requests per minute to the API. Default: 60
      APP_KEY: $SPEEDTEST_TRACKER_APP_KEY # Key used to encrypt and decrypt data. You can generate a key at https://speedtest-tracker.dev.
      APP_NAME: ${SPEEDTEST_TRACKER_APP_NAME:-Speedtest Tracker} # Used to define the application's name in the dashboard and in notifications.
      APP_TIMEZONE: ${SPEEDTEST_TRACKER_APP_TIMEZONE:-${TZ:-America/Chicago}} # Application timezone should be set if your database does not use UTC as its default timezone.
      APP_URL: ${SPEEDTEST_TRACKER_APP_URL:-} # URL used for links in emails and notifications.
      ASSET_URL: ${SPEEDTEST_TRACKER_ASSET_URL:-} # URL used for assets, needed when using a reverse proxy.
      CHART_BEGIN_AT_ZERO: ${SPEEDTEST_TRACKER_CHART_BEGIN_AT_ZERO:-true} # Begin the dashboard axis charts at zero. Default: true
      CHART_DATETIME_FORMAT: ${SPEEDTEST_TRACKER_CHART_DATETIME_FORMAT:-j/m G:i} # Set the formatting of timestamps in charts.
      CONTENT_WIDTH: ${SPEEDTEST_TRACKER_CONTENT_WIDTH:-7xl} # Width of the content section of each page. Can be set to any value found in the Filament docs. Default: 7xl
      DATETIME_FORMAT: ${SPEEDTEST_TRACKER_DATETIME_FORMAT:-j M Y, G:i:s} # Set the formatting of timestamps in tables and notifications.
      DB_CONNECTION: ${SPEEDTEST_TRACKER_DB_CONNECTION:-sqlite}
      DISPLAY_TIMEZONE: ${SPEEDTEST_TRACKER_DISPLAY_TIMEZONE:-${TZ:-America/Chicago}} # Display timestamps in your local time.
      PRUNE_RESULTS_OLDER_THAN: ${SPEEDTEST_TRACKER_PRUNE_RESULTS_OLDER_THAN:-0} # Set the value to greater than zero to prune stored results. This value should be represented in days.
      PUBLIC_DASHBOARD: ${SPEEDTEST_TRACKER_PUBLIC_DASHBOARD:-true} # Enables the public dashboard for guest (unauthenticated) users. Default: false
      SPEEDTEST_BLOCKED_SERVERS: ${SPEEDTEST_TRACKER_BLOCKED_SERVERS:-} # Comma separated list of server IDs that should not be used when running speedtests.
      SPEEDTEST_INTERFACE: ${SPEEDTEST_TRACKER_INTERFACE:-} # Set the network interface to use for the test. This need to be the network interface available inside the container
      SPEEDTEST_SCHEDULE: ${SPEEDTEST_TRACKER_SCHEDULE:-6 */2 * * *} # Cron expression used to run speedtests on a scheduled basis.
      SPEEDTEST_SERVERS: ${SPEEDTEST_TRACKER_SERVERS:-} # Comma separated list of server IDs to randomly use for speedtest.
      SPEEDTEST_SKIP_IPS: ${SPEEDTEST_TRACKER_SKIP_IPS:-} # A comma separated list of public IP addresses where tests will be skipped when present.
      THRESHOLD_DOWNLOAD: ${SPEEDTEST_TRACKER_THRESHOLD_DOWNLOAD:-900} # Set the Download Threshold. Note: Only effective during initial setup.
      THRESHOLD_ENABLED: ${SPEEDTEST_TRACKER_THRESHOLD_ENABLED:-true} # Enable the thresholds. Note: Only effective during initial setup.
      THRESHOLD_PING: ${SPEEDTEST_TRACKER_THRESHOLD_PING:-25} # Set the Ping Threshold. Note: Only effective during initial setup.
      THRESHOLD_UPLOAD: ${SPEEDTEST_TRACKER_THRESHOLD_UPLOAD:-900} # Set the Upload Threshold. Note: Only effective during initial setup.
    labels:
      <<: *speedtest-labels
      homepage.group: Network Monitoring
      homepage.name: Speedtest
      homepage.icon: speedtest.png
      homepage.href: https://speedtest.$DOMAIN
      homepage.description: Regularly tests your internet speed and tracks performance over time, helping you monitor your connection quality.
      homepage.widget.type: speedtest
      homepage.widget.url: https://speedtest.$DOMAIN
      homepage.widget.fields: '["download", "upload", "ping", "speedtest"]'
    deploy:
      <<: [*common-deploy, *swarm-resource-limits]
      labels:
        <<: *speedtest-labels
    healthcheck:
      test: curl -fSs http://localhost:80 > /dev/null || exit 1
      start_period: 20s
      timeout: 5s
      interval: 5s
    restart: always