{{- $envFilePath := .Values.envFilePath | default "" -}}
{{- if and $envFilePath (.Files.Exists $envFilePath) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mediaflow-proxy.fullname" . }}-env
  labels:
    {{- include "mediaflow-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Data loaded from the file specified in .Values.envFilePath
  {{- $fileContent := .Files.Get $envFilePath }}
  {{- $lines := splitList "\n" $fileContent }}
  {{- range $lines }}
  {{- $line := trim . }}
  {{- if and $line (not (hasPrefix "#" $line)) }}
  {{- $pair := splitList "=" $line }}
  {{- if eq (len $pair) 2 }}
  {{ index $pair 0 | trim }}: {{ index $pair 1 | trim | quote }}
  {{- else if eq (len $pair) 1 }}
  {{ index $pair 0 | trim }}: ""
  {{- end }}
  {{- end }}
  {{- end }}
{{- else if $envFilePath }}
{{- /* Fail template processing if file path is specified but file doesn't exist */}}
{{- fail (printf "envFilePath '%s' specified but file does not exist in chart path" $envFilePath) }}
{{- end }} 