kind: Deploy
apiVersion: garden.io/v2
name: aiostreams
description: AIOStreams addon for Stremio
type: container

spec:
  image: ghcr.io/viren070/aiostreams:latest
  env:
    TZ: ${var.tz}
    PUID: ${var.PUID:-1001}
    PGID: ${var.PGID:-988}
    UMASK: ${var.UMASK:-002}
    
    # Essential addon setup
    ADDON_NAME: ${var.AIOSTREAMS_ADDON_NAME:-BadenAIO}
    ADDON_ID: aiostreams.${var.domain}
    PORT: ${var.AIOSTREAMS_PORT:-3000}
    BASE_URL: https://aiostreams.${var.domain}
    SECRET_KEY: ${var.AIOSTREAMS_SECRET_KEY}
    ADDON_PASSWORD: ${var.AIOSTREAMS_ADDON_PASSWORD}
    DATABASE_URI: sqlite://./data/db.sqlite
    
    # Built-in addon configuration
    BUILTIN_STREMTHRU_URL: https://stremthru.13377001.xyz
    BUILTIN_DEBRID_INSTANT_AVAILABILITY_CACHE_TTL: 1800
    BUILTIN_DEBRID_PLAYBACK_LINK_CACHE_TTL: 3600
    BUILTIN_GET_TORRENT_TIMEOUT: 5000
    BUILTIN_GET_TORRENT_CONCURRENCY: 100
    BUILTIN_PROWLARR_SEARCH_TIMEOUT: 
    BUILTIN_PROWLARR_SEARCH_CACHE_TTL: 604800
    BUILTIN_PROWLARR_INDEXERS_CACHE_TTL: 1209600
    
    # TMDB and Trakt API
    TMDB_ACCESS_TOKEN: ${var.TMDB_ACCESS_TOKEN}
    TMDB_API_KEY: ${var.TMDB_API_KEY}
    TRAKT_CLIENT_ID: 
    
    # Debrid service API keys
    DEFAULT_REALDEBRID_API_KEY: ${var.REALDEBRID_API_KEY}
    DEFAULT_ALLDEBRID_API_KEY: ${var.ALLDEBRID_API_KEY}
    DEFAULT_PREMIUMIZE_API_KEY: ${var.PREMIUMIZE_API_KEY}
    DEFAULT_DEBRIDLINK_API_KEY: ${var.DEBRIDLINK_API_KEY}
    DEFAULT_TORBOX_API_KEY: ${var.TORBOX_API_KEY}
    DEFAULT_OFFCLOUD_API_KEY: ${var.OFFCLOUD_API_KEY}
    DEFAULT_OFFCLOUD_EMAIL: ${var.OFFCLOUD_EMAIL}
    DEFAULT_OFFCLOUD_PASSWORD: ${var.OFFCLOUD_PASSWORD}
    DEFAULT_PUTIO_CLIENT_ID: ${var.PUTIO_CLIENT_ID}
    DEFAULT_PUTIO_CLIENT_SECRET: ${var.PUTIO_CLIENT_SECRET}
    DEFAULT_EASYNEWS_USERNAME: ${var.EASYNEWS_USERNAME:-}
    DEFAULT_EASYNEWS_PASSWORD: ${var.EASYNEWS_PASSWORD:-}
    DEFAULT_EASYDEBRID_API_KEY: ${var.EASYDEBRID_API_KEY}
    DEFAULT_PIKPAK_EMAIL: ${var.PIKPAK_EMAIL}
    DEFAULT_PIKPAK_PASSWORD: ${var.PIKPAK_PASSWORD}
    DEFAULT_SEEDR_ENCODED_TOKEN: ${var.SEEDR_ENCODED_TOKEN}
    
    # Customization & Access Control
    CUSTOM_HTML: ${var.AIOSTREAMS_CUSTOM_HTML:-}
    TRUSTED_UUIDS: ${var.AIOSTREAMS_TRUSTED_UUIDS:-}
    REGEX_FILTER_ACCESS: trusted
    
    # Stream proxy configuration
    FORCE_PROXY_ENABLED: true
    DEFAULT_PROXY_ID: stremthru
    DEFAULT_PROXY_CREDENTIALS: ${var.STREMTHRU_CREDENTIALS:-bolabaden:duckdns}
    FORCE_PROXY_DISABLE_PROXIED_ADDONS: false
    ENCRYPT_MEDIAFLOW_URLS: true
    ENCRYPT_STREMTHRU_URLS: true
    
    # Advanced configuration
    DEFAULT_TIMEOUT: 15000
    MAX_ADDONS: 100
    MAX_GROUPS: 50
    MAX_KEYWORD_FILTERS: 50
    MAX_STREAM_EXPRESSION_FILTERS: 200
    MAX_TIMEOUT: 50000
    MIN_TIMEOUT: 1000
    PRECACHE_NEXT_EPISODE_MIN_INTERVAL: 86400
    
    # Rate limit configuration
    DISABLE_RATE_LIMITS: false
    STATIC_RATE_LIMIT_WINDOW: 5
    STATIC_RATE_LIMIT_MAX_REQUESTS: 75
    USER_API_RATE_LIMIT_WINDOW: 5
    USER_API_RATE_LIMIT_MAX_REQUESTS: 5
    STREAM_API_RATE_LIMIT_WINDOW: 5
    STREAM_API_RATE_LIMIT_MAX_REQUESTS: 10
    FORMAT_API_RATE_LIMIT_WINDOW: 5
    FORMAT_API_RATE_LIMIT_MAX_REQUESTS: 30
    CATALOG_API_RATE_LIMIT_WINDOW: 5
    CATALOG_API_RATE_LIMIT_MAX_REQUESTS: 5
    ANIME_API_RATE_LIMIT_WINDOW: 60
    ANIME_API_RATE_LIMIT_MAX_REQUESTS: 120
    STREMIO_STREAM_RATE_LIMIT_WINDOW: 15
    STREMIO_STREAM_RATE_LIMIT_MAX_REQUESTS: 10
    STREMIO_CATALOG_RATE_LIMIT_WINDOW: 5
    STREMIO_CATALOG_RATE_LIMIT_MAX_REQUESTS: 30
    STREMIO_MANIFEST_RATE_LIMIT_WINDOW: 5
    STREMIO_MANIFEST_RATE_LIMIT_MAX_REQUESTS: 5
    STREMIO_SUBTITLE_RATE_LIMIT_WINDOW: 5
    STREMIO_SUBTITLE_RATE_LIMIT_MAX_REQUESTS: 10
    STREMIO_META_RATE_LIMIT_WINDOW: 5
    STREMIO_META_RATE_LIMIT_MAX_REQUESTS: 15
    
    # User pruning
    PRUNE_INTERVAL: 86400
    PRUNE_MAX_DAYS: -1
    
    # External addon URLs
    STREMTHRU_STORE_URL: ${var.STREMTHRU_STORE_HOST:-https://stremthru.${var.domain}/stremio/store/}
    STREMTHRU_TORZ_URL: ${var.STREMTHRU_TORZ_HOST:-https://stremthru.${var.domain}/stremio/torz/}
    DEFAULT_JACKETTIO_INDEXERS: '["animetosho", "anirena", "bitsearch", "eztv", "nyaasi", "thepiratebay", "therarbg", "yts"]'
    
    # Anime database
    ANIME_DB_LEVEL_OF_DETAIL: required
    ANIME_DB_FRIBB_MAPPINGS_REFRESH_INTERVAL: 86400000
    ANIME_DB_MANAMI_DB_REFRESH_INTERVAL: 604800000
    ANIME_DB_KITSU_IMDB_MAPPING_REFRESH_INTERVAL: 86400000
    ANIME_DB_EXTENDED_ANITRAKT_MOVIES_REFRESH_INTERVAL: 86400000
    ANIME_DB_EXTENDED_ANITRAKT_TV_REFRESH_INTERVAL: 86400000
    
    # Logging
    LOG_LEVEL: info
    LOG_FORMAT: text
    LOG_SENSITIVE_INFO: true
    LOG_TIMEZONE: Etc/UTC
    
    # Cache configuration
    DEFAULT_MAX_CACHE_SIZE: 100000
    PROXY_IP_CACHE_TTL: 900
    MANIFEST_CACHE_TTL: 300
    SUBTITLE_CACHE_TTL: 300
    STREAM_CACHE_TTL: 1
    CATALOG_CACHE_TTL: 300
    META_CACHE_TTL: 300
    ADDON_CATALOG_CACHE_TTL: 300
    RPDB_API_KEY_VALIDITY_CACHE_TTL: 604800
    
    # Feature control
    DISABLE_SELF_SCRAPING: true
    MEDIAFUSION_API_PASSWORD: ${var.sudo-password}
  ports:
    - name: http
      containerPort: 3000
  volumes:
    - name: data
      containerPath: /app/data
      sourcePath: ${var.config-path}/stremio/addons/aiostreams/data
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      memory: 50Mi
  ingresses:
    - path: /
      port: http
      hostname: aiostreams.${var.domain}
  restartPolicy: always

