kind: Deploy
apiVersion: garden.io/v0
name: flaresolverr
description: FlareSolverr proxy for bypassing Cloudflare challenges
type: container

spec:
  replicas: 3
  image: ghcr.io/flaresolverr/flaresolverr
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    TZ: ${var.tz}
    PUID: ${var.PUID || "1001"}
    PGID: ${var.PGID || "988"}
    UMASK: ${var.UMASK || "002"}
    LOG_LEVEL: debug
    LOG_HTML: false
    CAPTCHA_SOLVER: none
    PORT: ${var.FLARESOLVERR_PORT || "8191"}
    HOST: 0.0.0.0
    HEADLESS: ${var.FLARESOLVERR_HEADLESS || "true"}
    BROWSER_TIMEOUT: ${var.FLARESOLVERR_BROWSER_TIMEOUT || "120000"}
    TEST_URL: ${var.FLARESOLVERR_TEST_URL || "https://www.google.com"}
    PROMETHEUS_ENABLED: ${var.FLARESOLVERR_PROMETHEUS_ENABLED || "true"}
    PROMETHEUS_PORT: ${var.PROMETHEUS_PORT || "9090"}
  ports:
    - name: http
      containerPort: ${var.FLARESOLVERR_PORT || "8191"}
  resources:
    limits:
      cpu: 600m
      memory: 1Gi
    requests:
      memory: 64Mi
  ingresses:
    - path: /
      port: http
      hostname: flaresolverr.${var.domain}
    - path: /
      port: http
      hostname: flaresolverr.${var.ts-hostname}.${var.domain}
  healthCheck:
    exec:
      command:
      - sh
      - -c
      - 'curl -f http://127.0.0.1:${var.FLARESOLVERR_PORT || "8191"}/health > /dev/null 2>&1 || exit 1'
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 15
    failureThreshold: 3
    startPeriodSeconds: 60
  restartPolicy: always
