kind: Deploy
apiVersion: garden.io/v2
name: flaresolverr
description: FlareSolverr proxy for bypassing Cloudflare challenges
type: container

spec:
  image: ghcr.io/flaresolverr/flaresolverr:latest
  env:
    TZ: ${var.tz}
    PUID: ${var.PUID || "1001"}
    PGID: ${var.PGID || "988"}
    UMASK: ${var.UMASK || "002"}
    LOG_LEVEL: debug
    LOG_HTML: false
    CAPTCHA_SOLVER: none
    PORT: ${var.FLARESOLVERR_PORT || "8191"}
    HOST: 0.0.0.0
    HEADLESS: ${var.FLARESOLVERR_HEADLESS || "true"}
    BROWSER_TIMEOUT: ${var.FLARESOLVERR_BROWSER_TIMEOUT || "120000"}
    TEST_URL: ${var.FLARESOLVERR_TEST_URL || "https://www.google.com"}
    PROMETHEUS_ENABLED: ${var.FLARESOLVERR_PROMETHEUS_ENABLED || "true"}
    PROMETHEUS_PORT: ${var.PROMETHEUS_PORT || "9090"}
  ports:
    - name: http
      containerPort: 8191
  resources:
    limits:
      cpu: 600m
      memory: 1Gi
    requests:
      memory: 64Mi
  ingresses:
    - path: /
      port: http
      hostname: flaresolverr.${var.domain}
  healthCheck:
    httpGet:
      path: /health
      port: http
  restartPolicy: always
