kind: Deploy
apiVersion: garden.io/v2
name: mediaflow-proxy
description: MediaFlow proxy for M3U/HLS/HSTS normalization
type: container

spec:
  image: docker.io/mhdzumair/mediaflow-proxy
  env:
    TZ: ${var.tz}
    PUID: ${var.PUID:-1001}
    PGID: ${var.PGID:-988}
    UMASK: ${var.UMASK:-002}
    PORT: ${var.MEDIAFLOW_PROXY_PORT:-8888}
    API_PASSWORD: ${var.MEDIAFLOW_PROXY_API_PASSWORD}
    ENABLE_STREAMING_PROGRESS: ${var.MEDIAFLOW_PROXY_ENABLE_STREAMING_PROGRESS:-true}
  ports:
    - name: http
      containerPort: 8888
      hostPort: 8888
      hostIp: 127.0.0.1
  ingresses:
    - path: /
      port: http
      hostname: mediaflow-proxy.${var.domain}
  healthCheck:
    exec:
      command: [python3, -c, "import socket; s=socket.socket(); s.connect(('127.0.0.1', ${var.MEDIAFLOW_PROXY_PORT:-8888})); print('Healthcheck passed')"]
  restartPolicy: always

