kind: Deploy
apiVersion: garden.io/v0
name: prowlarr
description: Prowlarr indexer proxy and manager
type: container

spec:
  replicas: 3
  image: lscr.io/linuxserver/prowlarr
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    TZ: ${var.tz}
    PUID: ${var.PUID || "1001"}
    PGID: ${var.PGID || "988"}
  ports:
    - name: http
      containerPort: 9696
      hostPort: 9696
      hostIp: 127.0.0.1
  volumes:
    - name: config
      containerPath: /config
      sourcePath: ${var.config-path}/prowlarr/config
  resources:
    limits:
      cpu: 2000m
      memory: 6Gi
    requests:
      memory: 128Mi
  ingresses:
    - path: /
      port: http
      hostname: prowlarr.${var.domain}
    - path: /
      port: http
      hostname: prowlarr.${var.ts-hostname}.${var.domain}
  annotations:
    traefik.enable: "true"
    traefik.http.routers.prowlarr.rule: Host(`prowlarr.${var.domain}`) || Host(`prowlarr.${var.ts-hostname}.${var.domain}`)
    traefik.http.services.prowlarr.loadbalancer.server.port: "9696"
    kuma.prowlarr.http.name: prowlarr.${var.ts-hostname}.${var.domain}
    kuma.prowlarr.http.url: https://prowlarr.${var.domain}/api/v1/system/status
    kuma.prowlarr.http.interval: "60"
  healthCheck:
    exec:
      command: [sh, -c, "curl -fs -H \"Authorization: Bearer ${var.PROWLARR_API_KEY}\" http://127.0.0.1:9696/api/v1/system/status || exit 1"]
    initialDelaySeconds: 120
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
    startPeriodSeconds: 120
  restartPolicy: always

