kind: Run
apiVersion: garden.io/v2
name: rclone-init
description: Initialize rclone mounts
type: container
dependencies:
  - deploy.rclone

spec:
  image: ghcr.io/coanghel/rclone-docker-automount/rclone-init
  hostname: rclone-init
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    RCLONE_USERNAME: ""
    RCLONE_PASSWORD: ""
    RCLONE_PORT: ${var.RCLONE_PORT || "5572"}
    RCLONE_CONFIG_PATH: /config/rclone/rclone.conf
  volumes:
    - name: remote-mounts
      containerPath: /mnt/remote
      hostPath: /mnt/remote
    - name: mounts-config
      containerPath: /app/mounts.json
      hostPath: ${var.config-path}/rclone/mounts.json
      readOnly: true
  healthCheck:
    exec:
      command: [sh, -c, "mountpoint -q /mnt/remote"]
    initialDelaySeconds: 0
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 2
    startPeriodSeconds: 15
  restartPolicy: always

