kind: Deploy
apiVersion: garden.io/v0
name: rclone
description: Rclone cloud storage mount service
type: container

spec:
  replicas: 3
  image: docker.io/rclone/rclone:1.71
  extraHosts:
    - host.docker.internal:host-gateway
  capAdd:
    - SYS_ADMIN
  securityOpt:
    - apparmor:unconfined
  env:
    TZ: ${var.tz}
  ports:
    - name: http
      containerPort: ${var.RCLONE_PORT || "5572"}
  volumes:
    - name: hostfs
      containerPath: /hostfs
      sourcePath: /
      readOnly: true
    - name: etc-group
      containerPath: /etc/group
      sourcePath: /etc/group
      readOnly: true
    - name: etc-passwd
      containerPath: /etc/passwd
      sourcePath: /etc/passwd
      readOnly: true
    - name: remote-mounts
      containerPath: /mnt/remote
      sourcePath: /mnt/remote
    - name: cache
      containerPath: /.cache
      sourcePath: ${var.config-path}/rclone/.cache
    - name: config
      containerPath: /config/rclone
      sourcePath: ${var.config-path}/rclone/config/rclone
    - name: rclonefm-js
      containerPath: /var/lib/rclonefm/js
      sourcePath: ${var.config-path}/rclonefm/js
    - name: rclone-conf
      containerPath: /config/rclone/rclone.conf
      sourcePath: ${var.config-path}/rclone/rclone.conf
      readOnly: true
    - name: fuse-conf
      containerPath: /etc/fuse.conf
      sourcePath: /etc/fuse.conf
      readOnly: true
  devices:
    - name: fuse
      hostPath: /dev/fuse
      containerPath: /dev/fuse
  command:
    - rcd
    - --rc-web-gui
    - --rc-web-gui-no-open-browser
    - --rc-addr=:${var.RCLONE_PORT || "5572"}
    - --log-level=INFO
    - --rc-no-auth
    - --config=/config/rclone/rclone.conf
    - --cache-dir=/.cache/rclone
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      memory: 60Mi
  ingresses:
    - path: /
      port: http
      hostname: rclone.${var.domain}
    - path: /
      port: http
      hostname: rclone.${var.ts-hostname}.${var.domain}
  annotations:
    traefik.enable: "true"
    traefik.http.routers.rclone.middlewares: nginx-auth@file
    traefik.http.routers.rclone.rule: Host(`rclone.${var.domain}`) || Host(`rclone.${var.ts-hostname}.${var.domain}`)
    traefik.http.services.rclone.loadbalancer.server.port: ${var.RCLONE_PORT || "5572"}
    homepage.group: Cloud
    homepage.name: Rclone
    homepage.icon: rclone.png
    homepage.href: https://rclone.${var.domain}/
    homepage.description: A web interface for Rclone.
    homepage.weight: "0"
    kuma.rclone.http.name: rclone.${var.ts-hostname}.${var.domain}
    kuma.rclone.http.url: https://rclone.${var.domain}
    kuma.rclone.http.interval: "60"
  healthCheck:
    exec:
      command: [mountpoint, -q, /mnt/remote]
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 2
    startPeriodSeconds: 15
  restartPolicy: always

