kind: Deploy
apiVersion: garden.io/v2
name: stremthru
description: StremThru proxy bridge for Debrid services
type: container
dependencies:
  - deploy.redis

spec:
  image: docker.io/muniftanjim/stremthru:latest
  env:
    TZ: ${var.tz}
    PUID: ${var.PUID:-1001}
    PGID: ${var.PGID:-988}
    UMASK: ${var.UMASK:-002}
    
    # Base configuration
    STREMTHRU_BASE_URL: https://stremthru.${var.domain}
    
    # Logging configuration
    STREMTHRU_LOG_LEVEL: DEBUG
    STREMTHRU_LOG_FORMAT: text
    
    # Proxy configuration
    STREMTHRU_PROXY_AUTH: "${var.main-username}:${var.sudo-password},bolabaden:duckdns,bolabaden.duckdns@gmail.com:Hilogirl80"
    STREMTHRU_AUTH_ADMIN: ${var.main-username}
    STREMTHRU_STORE_AUTH: "*:realdebrid:${var.REALDEBRID_TOKEN},*:premiumize:${var.PREMIUMIZE_API_KEY},*:alldebrid:${var.ALLDEBRID_API_KEY},*:debridlink:${var.DEBRIDLINK_API_KEY},*:torbox:${var.TORBOX_API_KEY}"
    STREMTHRU_STORE_CONTENT_PROXY: "*:true,premiumize:false"
    STREMTHRU_CONTENT_PROXY_CONNECTION_LIMIT: "*:10"
    
    # Integration configuration
    STREMTHRU_INTEGRATION_TRAKT_CLIENT_ID: ${var.TRAKT_CLIENT_ID:-052d735c61c723ed670991aee9d6322822ed6766702d66910be63a1e1a511fd0}
    STREMTHRU_INTEGRATION_TRAKT_CLIENT_SECRET: ${var.TRAKT_CLIENT_SECRET:-1d5701574cae67023c25a3743f07669bb84ee74628fd8f0a3fc0c9cca51535c3}
    STREMTHRU_INTEGRATION_TRAKT_LIST_STALE_TIME: 12h
    STREMTHRU_INTEGRATION_TMDB_ACCESS_TOKEN: ${var.TMDB_ACCESS_TOKEN:-cec876f852b9c15d2c1b436b1117dff7}
    STREMTHRU_INTEGRATION_TMDB_LIST_STALE_TIME: 12h
    STREMTHRU_INTEGRATION_MDBLIST_LIST_STALE_TIME: 
    STREMTHRU_INTEGRATION_GITHUB_USER: th3w1zard1
    STREMTHRU_INTEGRATION_GITHUB_TOKEN: ${var.GITHUB_TOKEN}
    
    # Feature configuration
    STREMTHRU_STREMIO_TORZ_LAZY_PULL: true
    STREMTHRU_FEATURE: +anime,-stremio_p2p
    
    # Database configuration
    STREMTHRU_DATABASE_URI: ${var.STREMTHRU_DATABASE_URI:-sqlite://./data/stremthru.db}
    STREMTHRU_REDIS_URI: ${var.REDIS_INTERNAL_URL:-redis://redis:6379}
  ports:
    - name: http
      containerPort: 8080
  volumes:
    - name: data
      containerPath: /app/data
      hostPath: /mnt/remote/premiumize/stremthru/app/data
  ingresses:
    - path: /
      port: http
      hostname: stremthru.${var.domain}
  healthCheck:
    httpGet:
      path: /
      port: http
  restartPolicy: always

