kind: Deploy
apiVersion: garden.io/v0
name: stremthru
description: StremThru proxy bridge for Debrid services
type: container
dependencies:
  - deploy.redis

spec:
  replicas: 3
  image: docker.io/muniftanjim/stremthru
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    TZ: ${var.tz}
    PUID: ${var.PUID || "1001"}
    PGID: ${var.PGID || "988"}
    UMASK: ${var.UMASK || "002"}
    
    # Base configuration
    STREMTHRU_BASE_URL: https://stremthru.${var.domain}
    
    # Logging configuration
    STREMTHRU_LOG_LEVEL: INFO
    STREMTHRU_LOG_FORMAT: text
    
    # Proxy configuration
    STREMTHRU_PROXY_AUTH_FILE: /run/secrets/stremthru-proxy-auth
    STREMTHRU_AUTH_ADMIN: ${var.MAIN_USERNAME}
    STREMTHRU_STORE_AUTH_FILE: /run/secrets/stremthru-store-auth
    STREMTHRU_STORE_CONTENT_PROXY: "*:true,premiumize:false"
    STREMTHRU_CONTENT_PROXY_CONNECTION_LIMIT: "*:10"
    
    # Integration configuration
    STREMTHRU_INTEGRATION_TRAKT_CLIENT_ID: ${var.TRAKT_CLIENT_ID}
    STREMTHRU_INTEGRATION_TRAKT_CLIENT_SECRET: ${var.TRAKT_CLIENT_SECRET}
    STREMTHRU_INTEGRATION_TRAKT_LIST_STALE_TIME: 12h
    STREMTHRU_INTEGRATION_TMDB_ACCESS_TOKEN: ${var.TMDB_ACCESS_TOKEN}
    STREMTHRU_INTEGRATION_TMDB_LIST_STALE_TIME: 12h
    STREMTHRU_INTEGRATION_MDBLIST_LIST_STALE_TIME: 
    STREMTHRU_INTEGRATION_GITHUB_USER: th3w1zard1
    STREMTHRU_INTEGRATION_GITHUB_TOKEN: ${var.GITHUB_TOKEN}
    
    # Feature configuration
    STREMTHRU_STREMIO_TORZ_LAZY_PULL: true
    STREMTHRU_FEATURE: +anime,-stremio_p2p
    
    # Database configuration
    STREMTHRU_DATABASE_URI: ${var.STREMTHRU_DATABASE_URI || "sqlite://./data/stremthru.db"}
    STREMTHRU_REDIS_URI: ${var.REDIS_INTERNAL_URL || "redis://redis:6379"}
  ports:
    - name: http
      containerPort: 8080
  volumes:
    - name: data
      containerPath: /app/data
      sourcePath: ${var.config-path}/stremio/addons/stremthru/app/data
    - name: stremthru-proxy-auth
      containerPath: /run/secrets/stremthru-proxy-auth
      sourcePath: ${var.config-path}/secrets/stremthru-proxy-auth.txt
      readOnly: true
    - name: stremthru-store-auth
      containerPath: /run/secrets/stremthru-store-auth
      sourcePath: ${var.config-path}/secrets/stremthru-store-auth.txt
      readOnly: true
  ingresses:
    - path: /
      port: http
      hostname: stremthru.${var.domain}
    - path: /
      port: http
      hostname: stremthru.${var.ts-hostname}.${var.domain}
  annotations:
    traefik.enable: "true"
    traefik.http.routers.stremthru.rule: Host(`stremthru.${var.domain}`) || Host(`stremthru.${var.ts-hostname}.${var.domain}`)
    traefik.http.services.stremthru.loadbalancer.server.port: "8080"
    homepage.group: Stremio Addons
    homepage.name: StremThru
    homepage.icon: stremthru.png
    homepage.href: https://stremthru.${var.domain}/
    homepage.description: Tunnel/proxy bridge for Debrid services to unify access of streaming links through a single host.
    kuma.stremthru.http.name: stremthru.${var.ts-hostname}.${var.domain}
    kuma.stremthru.http.url: https://stremthru.${var.domain}
    kuma.stremthru.http.interval: "60"
  healthCheck:
    exec:
      command: [sh, -c, "wget -qO- http://127.0.0.1:8080 > /dev/null 2>&1 || exit 1"]
    initialDelaySeconds: 15
    periodSeconds: 60
    timeoutSeconds: 5
    failureThreshold: 3
    startPeriodSeconds: 15
  restartPolicy: always

