{
 "title": "Crowdsec Cyber Threat Insights",
 "description": "Cyber threat insights with Crowdsec, VictoriaMetrics and Grafana",
 "tags": [
  "crowdsec",
  "victoriametrics",
  "grafana",
  "cyber-threats"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(cs_lapi_decision, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Decisions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (country, asname, scenario, type, duration, scope, ip, traefik_routers, latitude, longitude, iprange, asnumber, instance) (cs_lapi_decision{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Decisions by Country",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (country) (cs_lapi_decision{instance=~\"$instance\"})",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Decisions by AS Name",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (asname) (cs_lapi_decision{instance=~\"$instance\"})",
     "legendFormat": "{{asname}}"
    }
   ]
  },
  {
   "title": "Decisions by Scenario",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (scenario) (cs_lapi_decision{instance=~\"$instance\"})",
     "legendFormat": "{{scenario}}"
    }
   ]
  },
  {
   "title": "Decisions by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (type) (cs_lapi_decision{instance=~\"$instance\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Decisions by Duration",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (duration) (cs_lapi_decision{instance=~\"$instance\"})",
     "legendFormat": "{{duration}}"
    }
   ]
  },
  {
   "title": "Decisions by Scope",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (scope) (cs_lapi_decision{instance=~\"$instance\"})",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Decisions by Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (latitude, longitude) (cs_lapi_decision{instance=~\"$instance\"})"
    }
   ]
  }
 ]
}