# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json



services:
  unsend-postgres:
    image: docker.io/postgres:16.3-alpine
    container_name: unsend-postgres
    hostname: unsend-postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - backend
      - publicnet
    volumes:
      - '${CONFIG_PATH:-./volumes}/unsend/postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'unsend'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 20s
      retries: 10
    restart: always
  unsend:
    depends_on:
      unsend-postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    image: docker.io/unsend/unsend
    container_name: unsend
    hostname: unsend
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - backend
      - publicnet
    expose:
      - 3000
    environment:
      API_RATE_LIMIT: '${API_RATE_LIMIT:-1}'
      AWS_ACCESS_KEY: '${AWS_ACCESS_KEY:?}'
      AWS_DEFAULT_REGION: '${AWS_DEFAULT_REGION:-us-east-1}'
      AWS_SECRET_KEY: '${AWS_SECRET_KEY:?}'
      DATABASE_URL: '${UNSEND_POSTGRES_URL:-postgresql://postgres:postgres@unsend-postgres:5432/unsend}'
      GITHUB_ID: '$UNSEND_GITHUB_ID'
      GITHUB_SECRET: '$UNSEND_GITHUB_SECRET'
      HOSTNAME: 0.0.0.0
      NEXT_PUBLIC_IS_CLOUD: '${NEXT_PUBLIC_IS_CLOUD:-false}'
      NEXTAUTH_SECRET: '${NEXTAUTH_SECRET:?}'
      REDIS_URL: '${REDIS_HOST:-redis://redis:6379}'
    labels:
      traefik.enable: true
      traefik.http.middlewares.gzip.compress: true
      traefik.http.routers.unsend.middlewares: gzip
      traefik.http.routers.unsend.service: unsend
      traefik.http.routers.unsend.rule: (Host(`unsend.$DOMAIN`) || Host(`unsend.$TS_HOSTNAME.$DOMAIN`)) && PathPrefix(`/`)
      traefik.http.services.unsend.loadbalancer.server.port: 3000
      kuma.unsend.http.name: ${UNSEND_FQDN:-unsend.$TS_HOSTNAME.$DOMAIN}
      kuma.unsend.http.url: ${UNSEND_URL:-https://unsend.$DOMAIN}
      kuma.unsend.http.interval: 5
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://unsend:3000 > /dev/null 2>&1 || exit 1"]
      interval: 5s
      retries: 10
      timeout: 2s
    restart: always
configs: {  }
secrets: {  }
volumes: {  }
