# Nomad job equivalent to compose/docker-compose.headscale.yml
# Extracted from nomad.hcl
# Variables are loaded from ../variables.nomad.hcl via -var-file
# This matches the include structure in docker-compose.yml

job "docker-compose.headscale" {
  datacenters = ["dc1"]
  type        = "service"

  # Note: Constraint removed - nodes may not expose consul.version attribute
  # Consul integration is verified via service discovery, not version constraint

  group "headscale-server-group" {
    count = 1

    network {
      mode = "bridge"
      
      port "headscale_stun" { to = 3478 }
      port "headscale_http" { to = 8081 }
      port "headscale_metrics" { to = 8080 }
      port "headscale_grpc" { to = 50443 }
    }

    # Headscale Server
    task "headscale-server" {
      driver = "docker"

      config {
        image = "docker.io/headscale/headscale:latest"
        ports = ["headscale_stun", "headscale_http", "headscale_metrics", "headscale_grpc"]
        command = "serve"
        args    = ["--config", "/etc/headscale/config.yaml"]
        extra_hosts = ["host.docker.internal:${attr.unique.network.ip-address}"]
        volumes = [
          "${var.root_path}/certs/private/${var.domain}.key:/var/lib/headscale/private.key",
          "${var.config_path}/headscale/config:/etc/headscale",
          "${var.config_path}/headscale/lib:/var/lib/headscale",
          "${var.config_path}/headscale/run:/var/run/headscale"
        ]
        labels = {
          "com.docker.compose.project" = "headscale-group"
          "com.docker.compose.service" = "headscale-server"
        }
      }

      # Headscale configuration template
      template {
        data = <<EOF
---
# headscale will look for a configuration file named `config.yaml` (or `config.json`) in the following order:
#
# - `/etc/headscale`
# - `~/.headscale`
# - current working directory

# The url clients will connect to.
# Typically this will be a domain like:
#
# https://myheadscale.example.com:443
#
#server_url: https://headscale-server.${var.domain}:443
server_url: http://headscale-server:{{ env "HEADSCALE_PORT" | or "8080" }}

# Address to listen to / bind to on the server
#
listen_addr: 0.0.0.0:{{ env "HEADSCALE_HTTP_PORT" | or "8081" }}

# Address to listen to /metrics and /debug, you may want
# to keep this endpoint private to your internal network
metrics_listen_addr: 127.0.0.1:{{ env "HEADSCALE_PORT" | or "8080" }}

# Address to listen for gRPC.
# gRPC is used for controlling a headscale server
# remotely with the CLI
# Note: Remote access _only_ works if you have
# valid certificates.

grpc_listen_addr: 0.0.0.0:{{ env "HEADSCALE_GRPC_PORT" | or "9090" }}

# Allow the gRPC admin interface to run in INSECURE
# mode. This is not recommended as the traffic will
# be unencrypted. Only enable if you know what you
# are doing.
grpc_allow_insecure: false

# Private key used encrypt the traffic between headscale
# and Tailscale clients.
# The private key file which will be
# autogenerated if it's missing
private_key_path: /var/lib/headscale/private.key

# The Noise section includes specific configuration for the
# TS2021 Noise protocol
noise:
  # The Noise private key is used to encrypt the traffic between headscale and
  # Tailscale clients when using the new Noise-based protocol. A missing key
  # will be automatically generated.
  private_key_path: /var/lib/headscale/noise_private.key

# List of IP prefixes to allocate tailaddresses from.
# Each prefix consists of either an IPv4 or IPv6 address,
# and the associated prefix length, delimited by a slash.
# It must be within IP ranges supported by the Tailscale
# client - i.e., subnets of 100.64.0.0/10 and fd7a:115c:a1e0::/48.
# See below:
# IPv6: https://github.com/tailscale/tailscale/blob/22ebb25e833264f58d7c3f534a8b166894a89536/net/tsaddr/tsaddr.go#LL81C52-L81C71
# IPv4: https://github.com/tailscale/tailscale/blob/22ebb25e833264f58d7c3f534a8b166894a89536/net/tsaddr/tsaddr.go#L33
# Any other range is NOT supported, and it will cause unexpected issues.
prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

  # Strategy used for allocation of IPs to nodes, available options:
  # - sequential (default): assigns the next free IP from the previous given IP.
  # - random: assigns the next free IP from a pseudo-random IP generator (crypto/rand).
  allocation: random

# DERP is a relay system that Tailscale uses when a direct
# connection cannot be established.
# https://tailscale.com/blog/how-tailscale-works/#encrypted-tcp-relays-derp
#
# headscale needs a list of DERP servers that can be presented
# to the clients.
derp:
  server:
    # If enabled, runs the embedded DERP server and merges it into the rest of the DERP config
    # The Headscale server_url defined above MUST be using https, DERP requires TLS to be in place
    enabled: false

    # Region ID to use for the embedded DERP server.
    # The local DERP prevails if the region ID collides with other region ID coming from
    # the regular DERP config.
    region_id: 999

    # Region code and name are displayed in the Tailscale UI to identify a DERP region
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"

    # Listens over UDP at the configured address for STUN connections - to help with NAT traversal.
    # When the embedded DERP server is enabled stun_listen_addr MUST be defined.
    #
    # For more details on how this works, check this great article: https://tailscale.com/blog/how-tailscale-works/
    stun_listen_addr: "0.0.0.0:{{ env "HEADSCALE_STUN_PORT" | or "3478" }}"

    # Private key used to encrypt the traffic between headscale DERP and
    # Tailscale clients. A missing key will be automatically generated.
    private_key_path: /var/lib/headscale/derp_server_private.key

    # This flag can be used, so the DERP map entry for the embedded DERP server is not written automatically,
    # it enables the creation of your very own DERP map entry using a locally available file with the parameter DERP.paths
    # If you enable the DERP server and set this to false, it is required to add the DERP server to the DERP map using DERP.paths
    automatically_add_embedded_derp_region: true

    # For better connection stability (especially when using an Exit-Node and DNS is not working),
    # it is possible to optionally add the public IPv4 and IPv6 address to the Derp-Map using:
    ipv4: 100.64.0.2
    ipv6: fd7a:115c:a1e0::2

  # List of externally available DERP maps encoded in JSON
  urls:
    - https://controlplane.tailscale.com/derpmap/default

  # Locally available DERP map files encoded in YAML
  #
  # This option is mostly interesting for people hosting
  # their own DERP servers:
  # https://tailscale.com/kb/1118/custom-derp-servers/
  #
  # paths:
  #   - /etc/headscale/derp-example.yaml
  paths: []

  # If enabled, a worker will be set up to periodically
  # refresh the given sources and update the derpmap
  # will be set up.
  auto_update_enabled: true

  # How often should we check for DERP updates?
  update_frequency: 24h

# Disables the automatic check for headscale updates on startup
disable_check_updates: false

# Time before an inactive ephemeral node is deleted?
ephemeral_node_inactivity_timeout: 30m

database:
  # Database type. Available options: sqlite, postgres
  # Please note that using Postgres is highly discouraged as it is only supported for legacy reasons.
  # All new development, testing and optimisations are done with SQLite in mind.
  type: sqlite

  # Enable debug mode. This setting requires the log.level to be set to "debug" or "trace".
  debug: {{ env "HEADSCALE_DEBUG" | or "false" }}

  # GORM configuration settings.
  gorm:
    # Enable prepared statements.
    prepare_stmt: {{ env "HEADSCALE_PREPARE_STMT" | or "true" }}

    # Enable parameterized queries.
    parameterized_queries: {{ env "HEADSCALE_PARAMETERIZED_QUERIES" | or "true" }}

    # Skip logging "record not found" errors.
    skip_err_record_not_found: {{ env "HEADSCALE_SKIP_ERR_RECORD_NOT_FOUND" | or "true" }}

    # Threshold for slow queries in milliseconds.
    slow_threshold: {{ env "HEADSCALE_SLOW_THRESHOLD" | or "1000" }}

  # SQLite config
  sqlite:
    path: /var/lib/headscale/db.sqlite

    # Enable WAL mode for SQLite. This is recommended for production environments.
    # https://www.sqlite.org/wal.html
    write_ahead_log: {{ env "HEADSCALE_WRITE_AHEAD_LOG" | or "true" }}

    # Maximum number of WAL file frames before the WAL file is automatically checkpointed.
    # https://www.sqlite.org/c3ref/wal_autocheckpoint.html
    # Set to 0 to disable automatic checkpointing.
    wal_autocheckpoint: {{ env "HEADSCALE_WAL_AUTOCHECKPOINT" | or "1000" }}

log:
  # Output formatting for logs: text or json
  format: {{ env "HEADSCALE_LOG_FORMAT" | or "text" }}
  level: {{ env "HEADSCALE_LOG_LEVEL" | or "info" }}

## Policy
# headscale supports Tailscale's ACL policies.
# Please have a look to their KB to better
# understand the concepts: https://tailscale.com/kb/1018/acls/
policy:
  # The mode can be "file" or "database" that defines
  # where the ACL policies are stored and read from.
  mode: {{ env "HEADSCALE_POLICY_MODE" | or "file" }}
  # If the mode is set to "file", the path to a
  # HuJSON file containing ACL policies.
  path: {{ env "HEADSCALE_POLICY_PATH" | or "" }}

## DNS
#
# headscale supports Tailscale's DNS configuration and MagicDNS.
# Please have a look to their KB to better understand the concepts:
#
# - https://tailscale.com/kb/1054/dns/
# - https://tailscale.com/kb/1081/magicdns/
# - https://tailscale.com/blog/2021-09-private-dns-with-magicdns/
#
# Please note that for the DNS configuration to have any effect,
# clients must have the `--accept-dns=true` option enabled. This is the
# default for the Tailscale client. This option is enabled by default
# in the Tailscale client.
#
# Setting _any_ of the configuration and `--accept-dns=true` on the
# clients will integrate with the DNS manager on the client or
# overwrite /etc/resolv.conf.
# https://tailscale.com/kb/1235/resolv-conf
#
# If you want stop Headscale from managing the DNS configuration
# all the fields under `dns` should be set to empty values.
dns:
  # Whether to use [MagicDNS](https://tailscale.com/kb/1081/magicdns/).
  magic_dns: {{ env "HEADSCALE_MAGIC_DNS" | or "true" }}

  # Defines the base domain to create the hostnames for MagicDNS.
  # This domain _must_ be different from the server_url domain.
  # `base_domain` must be a FQDN, without the trailing dot.
  # The FQDN of the hosts will be
  # `hostname.base_domain` (e.g., _myhost.example.com_).
  base_domain: myscale.${var.domain}

  # Whether to use the local DNS settings of a node (default) or override the
  # local DNS settings and force the use of Headscale's DNS configuration.
  override_local_dns: {{ env "HEADSCALE_OVERRIDE_LOCAL_DNS" | or "false" }}

  # List of DNS servers to expose to clients.
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1
      - 2606:4700:4700::1111
      - 2606:4700:4700::1001

      # NextDNS (see https://tailscale.com/kb/1218/nextdns/).
      # "abc123" is example NextDNS ID, replace with yours.
      # - https://dns.nextdns.io/abc123

    # Split DNS (see https://tailscale.com/kb/1054/dns/),
    # a map of domains and which DNS server to use for each.
    split:
      {
#        "headscale.${var.domain}": [
#          "1.1.1.1",
#          "1.0.0.1",
#          "2606:4700:4700::1111",
#          "2606:4700:4700::1001"
#        ]
      }
      # foo.bar.com:
      #   - 1.1.1.1
      # darp.headscale.net:
      #   - 1.1.1.1
      #   - 8.8.8.8

  # Set custom DNS search domains. With MagicDNS enabled,
  # your tailnet base_domain is always the first search domain.
  search_domains: []

  # Extra DNS records
  # so far only A and AAAA records are supported (on the tailscale side)
  # See: docs/ref/dns.md
  extra_records: []
  #   - name: "grafana.myvpn.example.com"
  #     type: "A"
  #     value: "100.64.0.3"
  #
  #   # you can also put it in one line
  #   - { name: "prometheus.myvpn.example.com", type: "A", value: "100.64.0.3" }
  #
  # Alternatively, extra DNS records can be loaded from a JSON file.
  # Headscale processes this file on each change.
  # extra_records_path: /var/lib/headscale/extra-records.json

# Unix socket used for the CLI to connect without authentication
# Note: for production you will want to set this to something like:
unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"

# Logtail configuration
# Logtail is Tailscales logging and auditing infrastructure, it allows the control panel
# to instruct tailscale nodes to log their activity to a remote server.
logtail:
  # Enable logtail for this headscales clients.
  # As there is currently no support for overriding the log server in headscale, this is
  # disabled by default. Enabling this will make your clients send logs to Tailscale Inc.
  enabled: {{ env "HEADSCALE_LOGTAIL_ENABLED" | or "false" }}

# Enabling this option makes devices prefer a random port for WireGuard traffic over the
# default static port 41641. This option is intended as a workaround for some buggy
# firewall devices. See https://tailscale.com/kb/1181/firewalls/ for more information.
randomize_client_port: {{ env "HEADSCALE_RANDOMIZE_CLIENT_PORT" | or "false" }}
EOF
        destination = "local/config.yaml"
        perms       = "0644"
      }

      env {
        TZ = var.tz
      }

      resources {
        cpu        = 1
        memory     = 256
        memory_max = 0
      
      }

      service {
        name = "headscale-server"
        port = "headscale_http"
        tags = [
          "traefik.enable=true",
          "traefik.http.middlewares.headscale-admin-redirect.redirectRegex.regex=^https?://headscale(-server)?\\.(${var.domain}|${node.unique.name}\\.${var.domain})/admin(.*)$$",
          "traefik.http.middlewares.headscale-admin-redirect.redirectRegex.replacement=https://headscale.${var.domain}/web$$3",
          "traefik.http.middlewares.headscale-admin-redirect.redirectRegex.permanent=false",
          "traefik.http.middlewares.headscale-server-redirect.redirectRegex.regex=^https?://headscale-server\\.((?:${var.domain}|${node.unique.name}\\.${var.domain}))(.*)$$",
          "traefik.http.middlewares.headscale-server-redirect.redirectRegex.replacement=https://headscale.$$1$$2",
          "traefik.http.middlewares.headscale-server-redirect.redirectRegex.permanent=false",
          "traefik.http.routers.headscale-server.service=headscale-server@consulcatalog",
          "traefik.http.routers.headscale-server.rule=Host(`headscale-server.${var.domain}`) || Host(`headscale-server.${node.unique.name}.${var.domain}`) || Host(`headscale.${var.domain}`) || Host(`headscale.${node.unique.name}.${var.domain}`)",
          "traefik.http.routers.headscale-server.middlewares=headscale-admin-redirect@consulcatalog,headscale-server-redirect@consulcatalog",
          "traefik.http.services.headscale-server.loadbalancer.server.port=8081",
          "traefik.http.routers.headscale-metrics.service=headscale-metrics@consulcatalog",
          "traefik.http.routers.headscale-metrics.rule=(Host(`headscale.${var.domain}`) || Host(`headscale.${node.unique.name}.${var.domain}`)) && PathPrefix(`/metrics`)",
          "traefik.http.services.headscale-metrics.loadbalancer.server.port=8080"
        ]
      }
    }
  }
  group "headscale-group" {
    count = 1

    network {
      mode = "bridge"
      
      port "headscale" { to = 8080 }
      
      # DNS configuration from Docker
      dns {
        servers = [
          "1.1.1.1",
          "1.0.0.1",
          "2606:4700:4700::1111",
          "2606:4700:4700::1001",
          "9.9.9.9",
          "2620:fe::fe",
          "8.8.8.8",
          "2001:4860:4860::8888",
          "2001:4860:4860::8844"
        ]
      }
    }

    # Headscale UI (named "headscale" to match Docker naming)
    task "headscale" {
      driver = "docker"

      config {
        image = "ghcr.io/gurucomputing/headscale-ui:latest"
        ports = ["headscale"]
        extra_hosts = ["host.docker.internal:${attr.unique.network.ip-address}"]
        volumes = [
          "${var.config_path}/headscale/config:/etc/headscale"
        ]
        labels = {
          "com.docker.compose.project" = "headscale-group"
          "com.docker.compose.service" = "headscale"
        }
      }

      resources {
        cpu        = 1
        memory     = 256
        memory_max = 0
      
      }

      service {
        name = "headscale"
        port = "headscale"
        tags = [
          "traefik.enable=true",
          "traefik.http.routers.headscale.service=headscale",
          "traefik.http.routers.headscale.rule=(Host(`headscale.${var.domain}`) || Host(`headscale.${node.unique.name}.${var.domain}`)) && (PathPrefix(`/web`) || PathPrefix(`/web/users.html`) || PathPrefix(`/web/groups.html`) || PathPrefix(`/web/devices.html`) || PathPrefix(`/web/settings.html`))",
          "traefik.http.services.headscale.loadbalancer.server.port=8080",
          "homepage.group=Networking",
          "homepage.name=Headscale UI",
          "homepage.icon=headscale.png",
          "homepage.href=https://headscale.${var.domain}/",
          "homepage.description=Headscale UI is a web interface for Headscale, an open source implementation of Tailscale's Admin control panel."
        ]

        check {
          type     = "http"
          path     = "/web"
          interval = "30s"
          timeout  = "10s"
        }
      }
    }
  }
}
