kind: Deploy
apiVersion: garden.io/v0
name: authentik-worker
description: Authentik worker for background tasks
type: container
dependencies:
  - deploy.authentik-postgresql
  - deploy.redis

spec:
  replicas: 3
  image: ghcr.io/goauthentik/server:${var.AUTHENTIK_TAG || "2025.8.3"}
  hostname: authentik-worker
  extraHosts:
    - host.docker.internal:host-gateway
  runAsUser: 0
  env:
    AUTHENTIK_REDIS__HOST: redis
    AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
    AUTHENTIK_POSTGRESQL__USER: authentik
    AUTHENTIK_POSTGRESQL__NAME: authentik
    AUTHENTIK_POSTGRESQL__PASSWORD: authentik
    AUTHENTIK_SECRET_KEY: /run/secrets/authentik-secret-key
    AUTHENTIK_ERROR_REPORTING__ENABLED: true
    AUTHENTIK_EMAIL__HOST: smtp.gmail.com
    AUTHENTIK_EMAIL__PORT: 587
    AUTHENTIK_EMAIL__USERNAME: boden.crouch@gmail.com
    AUTHENTIK_EMAIL__PASSWORD: /run/secrets/gmail-app-password
    AUTHENTIK_EMAIL__USE_TLS: true
    AUTHENTIK_EMAIL__USE_SSL: false
    AUTHENTIK_EMAIL__TIMEOUT: 10
    AUTHENTIK_EMAIL__FROM: boden.crouch@gmail.com
    AUTHENTIK_BOOTSTRAP__EMAIL: boden.crouch@gmail.com
    AUTHENTIK_BOOTSTRAP__PASSWORD: /run/secrets/sudo-password
  volumes:
    - name: docker-sock
      containerPath: /var/run/docker.sock
      sourcePath: ${var.docker-socket}
      readOnly: false
    - name: media
      containerPath: /media
      sourcePath: ${var.config-path}/authentik/media
    - name: certs
      containerPath: /certs
      sourcePath: ${var.config-path}/authentik/certs
    - name: custom-templates
      containerPath: /templates
      sourcePath: ${var.config-path}/authentik/custom-templates
    - name: authentik-secret-key
      containerPath: /run/secrets/authentik-secret-key
      sourcePath: ${var.config-path}/secrets/authentik-secret-key.txt
      readOnly: true
    - name: gmail-app-password
      containerPath: /run/secrets/gmail-app-password
      sourcePath: ${var.config-path}/secrets/gmail-app-password.txt
      readOnly: true
    - name: sudo-password
      containerPath: /run/secrets/sudo-password
      sourcePath: ${var.config-path}/secrets/sudo-password.txt
      readOnly: true
  command: [worker]
  restartPolicy: always

