kind: Deploy
apiVersion: garden.io/v0
name: authentik-postgresql
description: PostgreSQL database for Authentik
type: container

spec:
  replicas: 3
  image: docker.io/postgres:16-alpine
  hostname: authentik-postgresql
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    POSTGRES_PASSWORD: authentik
    POSTGRES_USER: authentik
    POSTGRES_DB: authentik
  ports:
    - name: db
      containerPort: 5432
  volumes:
    - name: data
      containerPath: /var/lib/postgresql/data
      hostPath: ${var.config-path}/authentik/postgresql
  healthCheck:
    exec:
      command: [sh, -c, "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    initialDelaySeconds: 2
    periodSeconds: 2
    timeoutSeconds: 10
    failureThreshold: 15
  restartPolicy: always

