kind: Deploy
apiVersion: garden.io/v2
name: cloudflare-ddns
description: Cloudflare DDNS service for dynamic DNS updates
type: container

spec:
  image: docker.io/favonia/cloudflare-ddns:1
  networkMode: host
  readOnly: true
  capDrop: [all]
  securityOpt: [no-new-privileges:true]
  env:
    TZ: ${var.tz}
    CLOUDFLARE_API_TOKEN: ${var.CLOUDFLARE_API_TOKEN}
    DOMAINS: ${var.ts-hostname}.${var.domain},*.${var.ts-hostname}.${var.domain}
    PROXIED: is(${var.domain})||is(*.${var.domain})
    TTL: 1
    RECORD_COMMENT: 'Updated by Cloudflare DDNS on server `${var.ts-hostname}.${var.domain}`'
  restartPolicy: always
