kind: Deploy
apiVersion: garden.io/v2
name: tinyauth
description: TinyAuth authentication service
type: container

spec:
  image: ghcr.io/steveiliop56/tinyauth:v3
  env:
    SECRET: ${var.TINYAUTH_SECRET}
    APP_URL: https://auth.${var.domain}
    USERS: ${var.TINYAUTH_USERS}
    GOOGLE_CLIENT_ID: ${var.TINYAUTH_GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET: ${var.TINYAUTH_GOOGLE_CLIENT_SECRET}
    GITHUB_CLIENT_ID: ${var.TINYAUTH_GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${var.TINYAUTH_GITHUB_CLIENT_SECRET}
    SESSION_EXPIRY: ${var.TINYAUTH_SESSION_EXPIRY:-604800}
    COOKIE_SECURE: ${var.TINYAUTH_COOKIE_SECURE:-true}
    APP_TITLE: ${var.TINYAUTH_APP_TITLE:-${var.domain}}
    LOGIN_MAX_RETRIES: ${var.TINYAUTH_LOGIN_MAX_RETRIES:-15}
    LOGIN_TIMEOUT: ${var.TINYAUTH_LOGIN_TIMEOUT:-300}
    OAUTH_AUTO_REDIRECT: ${var.TINYAUTH_OAUTH_AUTO_REDIRECT:-none}
    OAUTH_WHITELIST: ${var.TINYAUTH_OAUTH_WHITELIST}
  ports:
    - name: http
      containerPort: 3000
  volumes:
    - name: data
      containerPath: /data
      sourcePath: ${var.config-path}/traefik/tinyauth
  ingresses:
    - path: /
      port: http
      hostname: auth.${var.domain}
  restartPolicy: always
