kind: Deploy
apiVersion: garden.io/v2
name: tinyauth
description: TinyAuth authentication service
type: container

spec:
  image: ghcr.io/steveiliop56/tinyauth:latest
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    SECRET_FILE: /run/secrets/tinyauth-secret
    APP_URL: ${var.TINYAUTH_APP_URL || "https://auth.${var.domain}"}
    USERS: ${var.TINYAUTH_USERS}
    GOOGLE_CLIENT_ID: ${var.TINYAUTH_GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET_FILE: /run/secrets/tinyauth-google-client-secret
    GITHUB_CLIENT_ID: ${var.TINYAUTH_GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET_FILE: /run/secrets/tinyauth-github-client-secret
    SESSION_EXPIRY: ${var.TINYAUTH_SESSION_EXPIRY || "604800"}
    COOKIE_SECURE: ${var.TINYAUTH_COOKIE_SECURE || "true"}
    APP_TITLE: ${var.TINYAUTH_APP_TITLE || "${var.domain}"}
    LOGIN_MAX_RETRIES: ${var.TINYAUTH_LOGIN_MAX_RETRIES || "15"}
    LOGIN_TIMEOUT: ${var.TINYAUTH_LOGIN_TIMEOUT || "300"}
    OAUTH_AUTO_REDIRECT: ${var.TINYAUTH_OAUTH_AUTO_REDIRECT || "none"}
    OAUTH_WHITELIST: ${var.TINYAUTH_OAUTH_WHITELIST}
  ports:
    - name: http
      containerPort: 3000
  volumes:
    - name: data
      containerPath: /data
      sourcePath: ${var.config-path}/traefik/tinyauth
    - name: tinyauth-secret
      containerPath: /run/secrets/tinyauth-secret
      sourcePath: ${var.config-path}/secrets/tinyauth-secret.txt
      readOnly: true
    - name: tinyauth-google-client-secret
      containerPath: /run/secrets/tinyauth-google-client-secret
      sourcePath: ${var.config-path}/secrets/tinyauth-google-client-secret.txt
      readOnly: true
    - name: tinyauth-github-client-secret
      containerPath: /run/secrets/tinyauth-github-client-secret
      sourcePath: ${var.config-path}/secrets/tinyauth-github-client-secret.txt
      readOnly: true
  ingresses:
    - path: /
      port: http
      hostname: auth.${var.domain}
  restartPolicy: always
