kind: Deploy
apiVersion: garden.io/v0
name: tinyauth
description: TinyAuth authentication service
type: container

spec:
  replicas: 3
  image: ghcr.io/steveiliop56/tinyauth:latest
  hostname: auth
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    SECRET_FILE: /run/secrets/tinyauth-secret
    APP_URL: ${var.TINYAUTH_APP_URL || "https://auth.${var.domain}"}
    USERS: ${var.TINYAUTH_USERS}
    GOOGLE_CLIENT_ID: ${var.TINYAUTH_GOOGLE_CLIENT_ID}
    GOOGLE_CLIENT_SECRET_FILE: /run/secrets/tinyauth-google-client-secret
    GITHUB_CLIENT_ID: ${var.TINYAUTH_GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET_FILE: /run/secrets/tinyauth-github-client-secret
    SESSION_EXPIRY: ${var.TINYAUTH_SESSION_EXPIRY || "604800"}
    COOKIE_SECURE: ${var.TINYAUTH_COOKIE_SECURE || "true"}
    APP_TITLE: ${var.TINYAUTH_APP_TITLE || "${var.domain}"}
    LOGIN_MAX_RETRIES: ${var.TINYAUTH_LOGIN_MAX_RETRIES || "15"}
    LOGIN_TIMEOUT: ${var.TINYAUTH_LOGIN_TIMEOUT || "300"}
    OAUTH_AUTO_REDIRECT: ${var.TINYAUTH_OAUTH_AUTO_REDIRECT || "none"}
    OAUTH_WHITELIST: ${var.TINYAUTH_OAUTH_WHITELIST}
  ports:
    - name: http
      containerPort: 3000
  volumes:
    - name: data
      containerPath: /data
      hostPath: ${var.config-path}/traefik/tinyauth
    - name: tinyauth-secret
      containerPath: /run/secrets/tinyauth-secret
      hostPath: ${var.config-path}/secrets/tinyauth-secret.txt
      readOnly: true
    - name: tinyauth-google-client-secret
      containerPath: /run/secrets/tinyauth-google-client-secret
      hostPath: ${var.config-path}/secrets/tinyauth-google-client-secret.txt
      readOnly: true
    - name: tinyauth-github-client-secret
      containerPath: /run/secrets/tinyauth-github-client-secret
      hostPath: ${var.config-path}/secrets/tinyauth-github-client-secret.txt
      readOnly: true
  ingresses:
    - path: /
      port: http
      hostname: auth.${var.domain}
    - path: /
      port: http
      hostname: auth.${var.ts-hostname}.${var.domain}
  annotations:
    traefik.enable: "true"
    traefik.http.services.tinyauth.loadbalancer.server.port: "3000"
    traefik.http.routers.tinyauth.rule: Host(`auth.${var.domain}`) || Host(`auth.${var.ts-hostname}.${var.domain}`)
    traefik.http.middlewares.tinyauth.forwardAuth.address: http://auth:3000/api/auth/traefik
    homepage.group: Security
    homepage.name: TinyAuth
    homepage.icon: https://tinyauth.app/img/logo.png
    homepage.href: https://auth.${var.domain}/
    homepage.description: Centralized login service (email, Google, GitHub) used by Traefik auth middleware and apps
    kuma.tinyauth.http.name: auth.${var.ts-hostname}.${var.domain}
    kuma.tinyauth.http.url: https://auth.${var.domain}
    kuma.tinyauth.http.interval: "60"
  restartPolicy: always
