kind: Deploy
apiVersion: garden.io/v0
name: whoami
description: Whoami test service
type: container

spec:
  replicas: 3
  image: docker.io/traefik/whoami:latest
  hostname: whoami
  extraHosts:
    - host.docker.internal:host-gateway
  ports:
    - name: http
      containerPort: 80
  ingresses:
    - path: /
      port: http
      hostname: whoami.${var.domain}
    - path: /
      port: http
      hostname: whoami.${var.ts-hostname}.${var.domain}
  annotations:
    traefik.enable: "true"
    traefik.http.routers.whoami.service: whoami@docker
    traefik.http.services.whoami.loadBalancer.server.port: "80"
    homepage.group: Web Services
    homepage.name: whoami
    homepage.icon: whoami.png
    homepage.href: https://whoami.${var.domain}
    homepage.description: Request echo service used to verify reverse-proxy, headers, and auth middleware
    kuma.whoami.http.name: whoami.${var.ts-hostname}.${var.domain}
    kuma.whoami.http.url: https://whoami.${var.domain}
    kuma.whoami.http.interval: "60"
  restartPolicy: always
