kind: Deploy
apiVersion: garden.io/v0
name: whoami
description: Whoami test service
type: container

spec:
  replicas: 3
  image: docker.io/traefik/whoami:latest
  extraHosts:
    - host.docker.internal:host-gateway
  ports:
    - name: http
      containerPort: 80
  ingresses:
    - path: /
      port: http
      hostname: whoami.${var.domain}
  restartPolicy: always
