apiVersion: v1
kind: Service
metadata:
  name: {{ include "comet.fullname" . }}
  labels:
    {{ include "comet.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{ include "comet.selectorLabels" . | indent 4 }} 