services:
  api.test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      - FQDN=$SERVICE_FQDN_API
      - PORT=3000
      - DB_CONNECTION=postgres
      - TEST=$TEST
      - TEST_PASSWORD=$SERVICE_PASSWORD_TEST
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=database
      - POSTGRES_PASSWORD=password
  db:
    image: nginx
  another-api:
    image: nginx
