services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN:?NPM_TOKEN not set}
    ports:
      - "3000"
    environment:
      - PORT=3000
      - DB_CONNECTION=postgres
      - TEST=$TEST
      - TEST_PASSWORD=$SERVICE_PASSWORD_64_API
    volumes:
      - test_db:/var/lib/mysql
  analytics:
    image: nginx
    environment:
      - API_URL=$SERVICE_FQDN_API
