kind: Deploy
apiVersion: garden.io/v0
name: mariadb
description: MariaDB database for WordPress
type: container

spec:
  replicas: 3
  image: docker.io/mariadb:latest
  hostname: mariadb
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    MYSQL_ROOT_PASSWORD: ${var.WORDPRESS_DB_ROOT_PASSWORD}
    MYSQL_DATABASE: ${var.WORDPRESS_DB_NAME || "wordpress"}
    MYSQL_USER: ${var.WORDPRESS_DB_USER}
    MYSQL_PASSWORD: ${var.WORDPRESS_DB_PASSWORD}
  ports:
    - name: db
      containerPort: 3306
  volumes:
    - name: data
      containerPath: /var/lib/mysql
      hostPath: ${var.config-path}/wordpress/mariadb-data
  restartPolicy: always

