kind: Deploy
apiVersion: garden.io/v0
name: wordpress
description: WordPress CMS
type: container
dependencies:
  - deploy.mariadb

spec:
  replicas: 3
  image: docker.io/wordpress:latest
  hostname: wordpress
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    WORDPRESS_DB_HOST: mariadb:3306
    WORDPRESS_DB_USER: ${var.WORDPRESS_DB_USER}
    WORDPRESS_DB_PASSWORD: ${var.WORDPRESS_DB_PASSWORD}
    WORDPRESS_DB_NAME: ${var.WORDPRESS_DB_NAME || "wordpress"}
  ports:
    - name: http
      containerPort: 80
  volumes:
    - name: wordpress-files
      containerPath: /var/www/html
      hostPath: ${var.config-path}/wordpress/wordpress-files
  ingresses:
    - path: /
      port: http
      hostname: wordpress.${var.domain}
    - path: /
      port: http
      hostname: wordpress.${var.ts-hostname}.${var.domain}
  annotations:
    traefik.enable: "true"
    traefik.http.middlewares.gzip.compress: "true"
    traefik.http.routers.wordpress.middlewares: gzip
    traefik.http.routers.wordpress.rule: (Host(`wordpress.${var.domain}`) || Host(`wordpress.${var.ts-hostname}.${var.domain}`)) && PathPrefix(`/`)
    traefik.http.services.wordpress.loadbalancer.server.port: "80"
    kuma.wordpress.http.name: ${var.WORDPRESS_FQDN || "wordpress.${var.ts-hostname}.${var.domain}"}
    kuma.wordpress.http.url: ${var.WORDPRESS_URL || "https://wordpress.${var.domain}"}
    kuma.wordpress.http.interval: "10"
  healthCheck:
    exec:
      command: [sh, -c, "curl -f http://127.0.0.1:80 > /dev/null 2>&1 || exit 1"]
    initialDelaySeconds: 2
    periodSeconds: 2
    timeoutSeconds: 10
    failureThreshold: 10
  restartPolicy: always

