# HA etcd Cluster Configuration
# 3-node etcd cluster for zero SPOF

apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
spec:
  containers:
  - name: etcd
    image: registry.k8s.io/etcd:3.5.9-0
    command:
    - etcd
    - --name=etcd0
    - --data-dir=/var/lib/etcd
    - --listen-client-urls=https://127.0.0.1:2379,https://10.16.1.78:2379
    - --advertise-client-urls=https://10.16.1.78:2379
    - --listen-peer-urls=https://10.16.1.78:2380
    - --initial-advertise-peer-urls=https://10.16.1.78:2380
    - --initial-cluster=etcd0=https://10.16.1.78:2380,etcd1=https://10.16.1.79:2380,etcd2=https://10.16.1.80:2380
    - --initial-cluster-token=etcd-cluster-0
    - --initial-cluster-state=new
    - --client-cert-auth=true
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --peer-client-cert-auth=true
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
