apiVersion: garden.io/v2
kind: Project
name: my-media-stack

environments:
  - name: default
    variables:
      base-hostname: my-media-stack.local.demo.garden
      domain: ${var.base-hostname}
      ts-hostname: ${local.hostname}
      config-path: ./volumes
      certs-path: ./certs
      docker-socket: /var/run/docker.sock
      root-path: .
      src-path: ./src
      tz: America/Chicago
      stack-name: my-media-stack
      PUID: 1001
      PGID: 999
      UMASK: "002"
      
      # Common system variables
      sudo-password: ${env.SUDO_PASSWORD}
      main-username: ${env.MAIN_USERNAME}
      
      # Cloudflare variables
      CLOUDFLARE_API_TOKEN: ${env.CLOUDFLARE_API_TOKEN}
      ACME_RESOLVER_EMAIL: ${env.ACME_RESOLVER_EMAIL}
      CLOUDFLARE_EMAIL: ${env.CLOUDFLARE_EMAIL}
      CLOUDFLARE_API_KEY: ${env.CLOUDFLARE_API_KEY}
      CLOUDFLARE_ZONE_ID: ${env.CLOUDFLARE_ZONE_ID}
      
      # TinyAuth variables
      TINYAUTH_SECRET: ${env.TINYAUTH_SECRET}
      TINYAUTH_USERS: ${env.TINYAUTH_USERS}
      TINYAUTH_GOOGLE_CLIENT_ID: ${env.TINYAUTH_GOOGLE_CLIENT_ID}
      TINYAUTH_GOOGLE_CLIENT_SECRET: ${env.TINYAUTH_GOOGLE_CLIENT_SECRET}
      TINYAUTH_GITHUB_CLIENT_ID: ${env.TINYAUTH_GITHUB_CLIENT_ID}
      TINYAUTH_GITHUB_CLIENT_SECRET: ${env.TINYAUTH_GITHUB_CLIENT_SECRET}
      
      # AI/LLM variables
      OPEN_WEBUI_SECRET_KEY: ${env.OPEN_WEBUI_SECRET_KEY}
      MCPO_API_KEY: ${env.MCPO_API_KEY}
      LITELLM_MASTER_KEY: ${env.LITELLM_MASTER_KEY}
      ANTHROPIC_API_KEY: ${env.ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${env.OPENAI_API_KEY}
      GROQ_API_KEY: ${env.GROQ_API_KEY}
      PERPLEXITY_API_KEY: ${env.PERPLEXITY_API_KEY}
      DEEPSEEK_API_KEY: ${env.DEEPSEEK_API_KEY}
      MISTRAL_API_KEY: ${env.MISTRAL_API_KEY}
      GEMINI_API_KEY: ${env.GEMINI_API_KEY}
      OPENROUTER_API_KEY: ${env.OPENROUTER_API_KEY}
      
      # Monitoring variables
      GF_SECURITY_ADMIN_PASSWORD: ${env.GF_SECURITY_ADMIN_PASSWORD}
      REDIS_PASSWORD: ${env.REDIS_PASSWORD}
      
      # Firecrawl variables
      FIRECRAWL_BULL_AUTH_KEY: ${env.FIRECRAWL_BULL_AUTH_KEY}
      FIRECRAWL_TEST_API_KEY: ${env.FIRECRAWL_TEST_API_KEY}
      
      # Search variables
      SEARXNG_SECRET: ${env.SEARXNG_SECRET}
      
      # Media/Stremio variables
      JACKETT_API_KEY: ${env.JACKETT_API_KEY}
      PROWLARR_API_KEY: ${env.PROWLARR_API_KEY}
      TMDB_API_KEY: ${env.TMDB_API_KEY}
      TMDB_ACCESS_TOKEN: ${env.TMDB_ACCESS_TOKEN}
      REALDEBRID_API_KEY: ${env.REALDEBRID_API_KEY}
      REALDEBRID_TOKEN: ${env.REALDEBRID_TOKEN}
      ALLDEBRID_API_KEY: ${env.ALLDEBRID_API_KEY}
      PREMIUMIZE_API_KEY: ${env.PREMIUMIZE_API_KEY}
      DEBRIDLINK_API_KEY: ${env.DEBRIDLINK_API_KEY}
      TORBOX_API_KEY: ${env.TORBOX_API_KEY}
      OFFCLOUD_API_KEY: ${env.OFFCLOUD_API_KEY}
      OFFCLOUD_EMAIL: ${env.OFFCLOUD_EMAIL}
      OFFCLOUD_PASSWORD: ${env.OFFCLOUD_PASSWORD}
      PUTIO_CLIENT_ID: ${env.PUTIO_CLIENT_ID}
      PUTIO_CLIENT_SECRET: ${env.PUTIO_CLIENT_SECRET}
      EASYNEWS_USERNAME: ${env.EASYNEWS_USERNAME}
      EASYNEWS_PASSWORD: ${env.EASYNEWS_PASSWORD}
      EASYDEBRID_API_KEY: ${env.EASYDEBRID_API_KEY}
      PIKPAK_EMAIL: ${env.PIKPAK_EMAIL}
      PIKPAK_PASSWORD: ${env.PIKPAK_PASSWORD}
      SEEDR_ENCODED_TOKEN: ${env.SEEDR_ENCODED_TOKEN}
      AIOSTREAMS_SECRET_KEY: ${env.AIOSTREAMS_SECRET_KEY}
      AIOSTREAMS_ADDON_PASSWORD: ${env.AIOSTREAMS_ADDON_PASSWORD}
      MEDIAFLOW_PROXY_API_PASSWORD: ${env.MEDIAFLOW_PROXY_API_PASSWORD}
      STREMTHRU_PROXY_AUTH: ${env.STREMTHRU_PROXY_AUTH}
      STREMTHRU_CREDENTIALS: ${env.STREMTHRU_CREDENTIALS}
      
      # VPN variables
      WARP_LICENSE_KEY: ${env.WARP_LICENSE_KEY}
      
      # Authentik variables
      AUTHENTIK_SECRET_KEY: ${env.AUTHENTIK_SECRET_KEY}
      GMAIL_APP_PASSWORD: ${env.GMAIL_APP_PASSWORD}
      
      # WordPress variables
      WORDPRESS_DB_USER: ${env.WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${env.WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_ROOT_PASSWORD: ${env.WORDPRESS_DB_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${env.WORDPRESS_DB_NAME || "wordpress"}
      
      # Development tools
      CODESERVER_HASHED_PASSWORD: ${env.CODESERVER_HASHED_PASSWORD}
      CODESERVER_SUDO_PASSWORD_HASH: ${env.CODESERVER_SUDO_PASSWORD_HASH}
      CODESERVER_DEFAULT_WORKSPACE: ${env.CODESERVER_DEFAULT_WORKSPACE || "/workspace"}
      
      # External APIs
      GITHUB_TOKEN: ${env.GITHUB_TOKEN}
      TRAKT_CLIENT_ID: ${env.TRAKT_CLIENT_ID}
      TRAKT_CLIENT_SECRET: ${env.TRAKT_CLIENT_SECRET}
      TELEGRAM_BOT_TOKEN: ${env.TELEGRAM_BOT_TOKEN}
      TELEGRAM_CHAT_ID: ${env.TELEGRAM_CHAT_ID}
      PREMIUMIZE_OAUTH_CLIENT_ID: ${env.PREMIUMIZE_OAUTH_CLIENT_ID}
      PREMIUMIZE_OAUTH_CLIENT_SECRET: ${env.PREMIUMIZE_OAUTH_CLIENT_SECRET}

providers:
  - name: local-kubernetes
    environments: [default]
    buildMode: cluster-buildkit
    defaultHostname: ${var.base-hostname}
    copySecrets:
      - name: docker-config
        namespace: default
