kind: Deploy
apiVersion: garden.io/v0
name: homepage
description: Homepage dashboard for service overview
type: container
dependencies:
  - deploy.dockerproxy-ro

spec:
  replicas: 3
  image: ghcr.io/gethomepage/homepage
  env:
    DOCKER_HOST: tcp://dockerproxy-ro:2375
    HOMEPAGE_ALLOWED_HOSTS: "*"
    HOMEPAGE_VAR_TITLE: Bolabaden
    HOMEPAGE_VAR_SEARCH_PROVIDER: duckduckgo
    HOMEPAGE_VAR_HEADER_STYLE: glass
    HOMEPAGE_VAR_THEME: dark
    HOMEPAGE_CUSTOM_CSS: /app/config/custom.css
    HOMEPAGE_CUSTOM_JS: /app/config/custom.js
    HOMEPAGE_VAR_WEATHER_CITY: Iowa City
    HOMEPAGE_VAR_WEATHER_LAT: 41.661129
    HOMEPAGE_VAR_WEATHER_LONG: -91.5302
    HOMEPAGE_VAR_WEATHER_UNIT: fahrenheit
  ports:
    - name: http
      containerPort: 3000
  volumes:
    - name: config
      containerPath: /app/config
      sourcePath: ${var.config-path}/homepage
    - name: custom-css
      containerPath: /app/config/custom.css
      sourcePath: ${var.config-path}/homepage/custom.css
    - name: custom-js
      containerPath: /app/config/custom.js
      sourcePath: ${var.config-path}/homepage/custom.js
    - name: docker-yaml
      containerPath: /app/config/docker.yaml
      sourcePath: ${var.config-path}/homepage/docker.yaml
    - name: widgets-yaml
      containerPath: /app/config/widgets.yaml
      sourcePath: ${var.config-path}/homepage/widgets.yaml
    - name: settings-yaml
      containerPath: /app/config/settings.yaml
      sourcePath: ${var.config-path}/homepage/settings.yaml
    - name: bookmarks-yaml
      containerPath: /app/config/bookmarks.yaml
      sourcePath: ${var.config-path}/homepage/bookmarks.yaml
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
    requests:
      memory: 128Mi
  ingresses:
    - path: /
      port: http
      hostname: homepage.${var.domain}
  healthCheck:
    exec:
      command: [sh, -c, "wget -qO- http://127.0.0.1:3000 > /dev/null 2>&1 || exit 1"]
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 15
    failureThreshold: 3
  restartPolicy: always
