kind: Deploy
apiVersion: garden.io/v0
name: blackbox-exporter
description: Blackbox Exporter for endpoint monitoring
type: container

spec:
  image: docker.io/prom/blackbox-exporter
  extraHosts:
    - host.docker.internal:host-gateway
  ports:
    - name: http
      containerPort: 9115
  volumes:
    - name: config
      containerPath: ${var.BLACKBOX_INTERNAL_CONFIG_PATH || "/etc/blackbox_exporter/config.yml"}
      sourcePath: ${var.config-path}/blackbox-exporter/blackbox.yml
      readOnly: true
  command:
    - '--config.file=${var.BLACKBOX_INTERNAL_CONFIG_PATH || "/etc/blackbox_exporter/config.yml"}'
    - '--log.level=${var.BLACKBOX_LOG_LEVEL || "info"}'
    - '--log.format=${var.BLACKBOX_LOG_FORMAT || "logfmt"}'
  ingresses:
    - path: /
      port: http
      hostname: blackbox.${var.domain}
    - path: /
      port: http
      hostname: blackbox.${var.ts-hostname}.${var.domain}
  restartPolicy: always
