kind: Deploy
apiVersion: garden.io/v0
name: victoriametrics
description: VictoriaMetrics time series database
type: container
dependencies:
  - run.victoriametrics-init

spec:
  image: docker.io/victoriametrics/victoria-metrics:latest
  extraHosts:
    - host.docker.internal:host-gateway
  env:
    VM_RETENTION_PERIOD: ${var.VICTORIAMETRICS_RETENTION_PERIOD || "1y"}
    VM_MEMORY_ALLOWED_PERCENT: ${var.VICTORIAMETRICS_MEMORY_ALLOWED_PERCENT || "60"}
    VM_SEARCH_MAX_CONCURRENT_REQUESTS: ${var.VICTORIAMETRICS_SEARCH_MAX_CONCURRENT_REQUESTS || "8"}
    VM_INSERT_MAX_CONCURRENT_REQUESTS: ${var.VICTORIAMETRICS_INSERT_MAX_CONCURRENT_REQUESTS || "32"}
  ports:
    - name: http
      containerPort: 8428
  volumes:
    - name: storage
      containerPath: /storage
      sourcePath: ${var.config-path}/victoriametrics
  command:
    - "--bigMergeConcurrency=${var.VICTORIAMETRICS_BIG_MERGE_CONCURRENCY || \"0\"}"
    - "--dedup.minScrapeInterval=${var.VICTORIAMETRICS_DEDUP_MIN_SCRAPE_INTERVAL || \"0s\"}"
    - "--enableTCP6=${var.VICTORIAMETRICS_ENABLE_TCP6 || \"false\"}"
    - "--finalMergeDelay=${var.VICTORIAMETRICS_FINAL_MERGE_DELAY || \"0s\"}"
    - "--http.maxGracefulShutdownDuration=${var.VICTORIAMETRICS_MAX_GRACEFUL_SHUTDOWN_DURATION || \"7s\"}"
    - "--http.shutdownDelay=${var.VICTORIAMETRICS_SHUTDOWN_DELAY || \"0s\"}"
    - "--httpListenAddr=:${var.VICTORIAMETRICS_PORT || \"8428\"}"
    - "--influx.maxLineSize=${var.VICTORIAMETRICS_INFLUX_MAX_LINE_SIZE || \"262144\"}"
    - "--loggerFormat=${var.VICTORIAMETRICS_LOG_FORMAT || \"default\"}"
    - "--loggerLevel=${var.VICTORIAMETRICS_LOG_LEVEL || \"INFO\"}"
    - "--memory.allowedPercent=${var.VICTORIAMETRICS_MEMORY_ALLOWED_PERCENT || \"60\"}"
    - "--promscrape.maxScrapeSize=${var.VICTORIAMETRICS_PROMSCRAPE_MAX_SCRAPE_SIZE || \"16777216\"}"
    - "--retentionPeriod=${var.VICTORIAMETRICS_RETENTION_PERIOD || \"1y\"}"
    - "--search.maxConcurrentRequests=${var.VICTORIAMETRICS_SEARCH_MAX_CONCURRENT_REQUESTS || \"8\"}"
    - "--search.maxMemoryPerQuery=${var.VICTORIAMETRICS_SEARCH_MAX_MEMORY_PER_QUERY || \"1GB\"}"
    - "--search.maxPointsPerTimeseries=${var.VICTORIAMETRICS_SEARCH_MAX_POINTS_PER_TIMESERIES || \"30000\"}"
    - "--search.maxQueryDuration=${var.VICTORIAMETRICS_SEARCH_MAX_QUERY_DURATION || \"30s\"}"
    - "--search.maxSeries=${var.VICTORIAMETRICS_SEARCH_MAX_SERIES || \"30000\"}"
    - "--search.maxTagKeys=${var.VICTORIAMETRICS_SEARCH_MAX_TAG_KEYS || \"100000\"}"
    - "--search.maxTagValues=${var.VICTORIAMETRICS_SEARCH_MAX_TAG_VALUES || \"100000\"}"
    - "--search.maxUniqueTimeseries=${var.VICTORIAMETRICS_SEARCH_MAX_UNIQUE_TIMESERIES || \"300000\"}"
    - "--smallMergeConcurrency=${var.VICTORIAMETRICS_SMALL_MERGE_CONCURRENCY || \"0\"}"
    - "--storageDataPath=/storage"
  healthCheck:
    exec:
      command: [sh, -c, "wget --no-verbose --tries=1 --spider http://127.0.0.1:${var.VICTORIAMETRICS_PORT || \"8428\"}/health || exit 1"]
    initialDelaySeconds: 40
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 3
  restartPolicy: always
