name: Test Media Stack

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [package_updated]

jobs:
  test-stack:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull latest image
      run: docker pull th3w1zard1/bolabaden:latest

    - name: Start stack with healthchecks
      run: |
        docker run -d --name bolabaden th3w1zard1/bolabaden:latest
        # Wait for services to become healthy
        timeout 300 bash -c 'while [[ $(docker ps -q --filter "health=healthy" | wc -l) -lt 3 ]]; do sleep 10; done' || {
          docker ps -a
          docker logs bolabaden
          exit 1
        }

    - name: Verify service status
      run: |
        # Check key containers are running
        docker ps --format "table {{.Names}}\t{{.Status}}"
        
        # Additional checks after short delay
        sleep 30
        docker ps
        docker exec -T bolabaden curl -I http://localhost:8099/api/health

    - name: Tear down stack
      if: always()
      run: docker rm -f bolabaden