kind: Deploy
apiVersion: garden.io/v0
name: headscale-server
description: Headscale server for Tailscale
type: container

spec:
  replicas: 3
  image: docker.io/headscale/headscale
  hostname: headscale-server
  extraHosts:
    - host.docker.internal:host-gateway
  ports:
    - name: stun
      containerPort: ${var.HEADSCALE_STUN_PORT || "3478"}
    - name: http
      containerPort: ${var.HEADSCALE_HTTP_PORT || "8081"}
    - name: metrics
      containerPort: ${var.HEADSCALE_METRICS_PORT || "8080"}
    - name: grpc
      containerPort: ${var.HEADSCALE_GRPC_PORT || "50443"}
  volumes:
    - name: private-key
      containerPath: /var/lib/headscale/private.key
      sourcePath: ${var.certs-path}/private/${var.domain}.key
      readOnly: true
    - name: config-yaml
      containerPath: /etc/headscale/config.yaml
      sourcePath: ${var.config-path}/headscale/config.yaml
      readOnly: true
    - name: lib
      containerPath: /var/lib/headscale
      sourcePath: ${var.config-path}/headscale/lib
    - name: run
      containerPath: /var/run/headscale
      sourcePath: ${var.config-path}/headscale/run
  command: [serve, --config, /etc/headscale/config.yaml]
  ingresses:
    - path: /
      port: http
      hostname: headscale.${var.domain}
    - path: /
      port: http
      hostname: headscale.${var.ts-hostname}.${var.domain}
    - path: /metrics
      port: metrics
      hostname: headscale.${var.domain}
    - path: /metrics
      port: metrics
      hostname: headscale.${var.ts-hostname}.${var.domain}
  annotations:
    traefik.enable: "true"
    traefik.http.middlewares.headscale-admin-redirect.redirectRegex.regex: '^https?://headscale(-server)?\.(${var.domain}|${var.ts-hostname}\.${var.domain})/admin(.*)$'
    traefik.http.middlewares.headscale-admin-redirect.redirectRegex.replacement: https://headscale.${var.domain}/web$3
    traefik.http.middlewares.headscale-admin-redirect.redirectRegex.permanent: "false"
    traefik.http.middlewares.headscale-server-redirect.redirectRegex.regex: '^https?://headscale-server\.((?:${var.domain}|${var.ts-hostname}\.${var.domain}))(.*)$'
    traefik.http.middlewares.headscale-server-redirect.redirectRegex.replacement: https://headscale.$1$2
    traefik.http.middlewares.headscale-server-redirect.redirectRegex.permanent: "false"
    traefik.http.routers.headscale-server.service: headscale-server@docker
    traefik.http.routers.headscale-server.rule: Host(`headscale-server.${var.domain}`) || Host(`headscale-server.${var.ts-hostname}.${var.domain}`) || Host(`headscale.${var.domain}`) || Host(`headscale.${var.ts-hostname}.${var.domain}`)
    traefik.http.routers.headscale-server.middlewares: headscale-admin-redirect@docker,headscale-server-redirect@docker
    traefik.http.services.headscale-server.loadbalancer.server.port: ${var.HEADSCALE_HTTP_PORT || "8081"}
    traefik.http.routers.headscale-metrics.service: headscale-metrics@docker
    traefik.http.routers.headscale-metrics.rule: (Host(`headscale.${var.domain}`) || Host(`headscale.${var.ts-hostname}.${var.domain}`)) && PathPrefix(`/metrics`)
    traefik.http.services.headscale-metrics.loadbalancer.server.port: ${var.HEADSCALE_METRICS_PORT || "8080"}
  restartPolicy: always
