kind: Deploy
apiVersion: garden.io/v0
name: headscale-server
description: Headscale server for Tailscale
type: container

spec:
  image: docker.io/headscale/headscale
  extraHosts:
    - host.docker.internal:host-gateway
  ports:
    - name: stun
      containerPort: ${var.HEADSCALE_STUN_PORT || "3478"}
    - name: http
      containerPort: ${var.HEADSCALE_HTTP_PORT || "8081"}
    - name: metrics
      containerPort: ${var.HEADSCALE_METRICS_PORT || "8080"}
    - name: grpc
      containerPort: ${var.HEADSCALE_GRPC_PORT || "50443"}
  volumes:
    - name: private-key
      containerPath: /var/lib/headscale/private.key
      sourcePath: ${var.certs-path}/private/${var.domain}.key
      readOnly: true
    - name: config
      containerPath: /etc/headscale
      sourcePath: ${var.config-path}/headscale/config
    - name: config-yaml
      containerPath: /etc/headscale/config.yaml
      sourcePath: ${var.config-path}/headscale/config.yaml
      readOnly: true
    - name: lib
      containerPath: /var/lib/headscale
      sourcePath: ${var.config-path}/headscale/lib
    - name: run
      containerPath: /var/run/headscale
      sourcePath: ${var.config-path}/headscale/run
  command: [serve, --config, /etc/headscale/config.yaml]
  ingresses:
    - path: /
      port: http
      hostname: headscale.${var.domain}
    - path: /
      port: http
      hostname: headscale.${var.ts-hostname}.${var.domain}
    - path: /metrics
      port: metrics
      hostname: headscale.${var.domain}
    - path: /metrics
      port: metrics
      hostname: headscale.${var.ts-hostname}.${var.domain}
  restartPolicy: always
